/* Progressive enhancement of the admin layout, without changing page permissions. */
(()=>{
 const paths={dashboard:'M3 10 12 3l9 7v11h-6v-7H9v7H3z',performance:'M4 20V10m8 10V4m8 16v-7M2 21h20',students:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m8-8a4 4 0 0 1 0 8m5 10v-2a4 4 0 0 0-3-4',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m8-8a4 4 0 0 1 0 8',schedule:'M4 5h16v16H4zM16 3v4M8 3v4M4 11h16',revenue:'M3 7h18v14H3zM3 7V4h15M16 14h5',alerts:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2'};
 const svg=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
 function closeMobile(){if(matchMedia('(max-width:850px)').matches){document.body.classList.add('admin-nav-collapsed');syncToggle();}}
 function syncToggle(){const b=document.getElementById('adminMenuToggle');if(b)b.setAttribute('aria-expanded',String(!document.body.classList.contains('admin-nav-collapsed')));const side=document.querySelector('.sidebar');if(side&&document.body.classList.contains('admin-shell'))side.inert=matchMedia('(max-width:850px)').matches&&document.body.classList.contains('admin-nav-collapsed');}
 function enhance(){const admin=currentUser?.role==='admin';document.body.classList.toggle('admin-shell',admin);if(!admin){document.querySelector('.sidebar').inert=false;return;}if(!document.getElementById('adminMenuToggle')){document.body.classList.toggle('admin-nav-collapsed',matchMedia('(max-width:850px)').matches);const button=document.createElement('button');button.id='adminMenuToggle';button.className='admin-menu-toggle';button.type='button';button.setAttribute('aria-label','فتح أو طي القائمة الجانبية');button.setAttribute('aria-controls','navMenu');button.innerHTML=svg('M4 6h16M4 12h16M4 18h16');button.onclick=()=>{document.body.classList.toggle('admin-nav-collapsed');syncToggle();};document.querySelector('.topbar>div').prepend(button);const shade=document.createElement('button');shade.className='admin-nav-shade';shade.setAttribute('aria-label','إغلاق القائمة');shade.onclick=()=>{document.body.classList.add('admin-nav-collapsed');syncToggle();};document.querySelector('#appShell').append(shade);closeMobile();}document.querySelectorAll('#navMenu .nav-item').forEach(item=>{const id=item.dataset.pageId;item.querySelector('.nav-icon').innerHTML=svg(paths[id]||'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5');item.setAttribute('role','button');item.tabIndex=0;item.setAttribute('aria-label',pageTitles[id]||item.textContent);item.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();item.click();}};});syncToggle();}
 const originalRender=renderNav;renderNav=function(...args){const result=originalRender.apply(this,args);enhance();return result;};
 const originalNav=navTo;navTo=function(...args){const result=originalNav.apply(this,args);if(currentUser?.role==='admin'){document.querySelectorAll('#navMenu .nav-item').forEach(n=>n.setAttribute('aria-current',n.classList.contains('active')?'page':'false'));closeMobile();}return result;};
 const originalLogout=doLogout;doLogout=async function(...args){document.body.classList.remove('admin-shell','admin-nav-collapsed');document.querySelector('.sidebar').inert=false;return originalLogout.apply(this,args);};
 matchMedia('(max-width:850px)').addEventListener('change',e=>{if(e.matches)closeMobile();else syncToggle();});addEventListener('resize',syncToggle);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&currentUser?.role==='admin'){closeMobile();}});
})();
