/* Aggregate history supplied by administration. It never changes student records. */
const reviewObmHistory={
 practitioner_live:{name:'إدارة السلوك التنظيمي (الممارس) المباشر',batches:[['الدفعة الأولى',24],['الدفعة الثانية',21],['الدفعة الثالثة',12],['الدفعة الرابعة',58],['الدفعة الخامسة',29]],graduates:144,current:true},
 advanced_live:{name:'إدارة السلوك التنظيمي (المتقدم) المباشر',batches:[['الدفعة الأولى',11],['الدفعة الثانية',24]],graduates:13,active:22},
 practitioner_recorded:{name:'إدارة السلوك التنظيمي (الممارس) المسجل',batches:[['الدفعة الأولى · آيات + روزان',39],['الدفعة الثانية · د. ماني',27],['الدفعة الثالثة · مصعب',180]],graduates:97},
 advanced_recorded:{name:'إدارة السلوك التنظيمي (المتقدم) المسجل',batches:[['الدفعة الأولى',12,12],['الدفعة الثانية',1,1]],graduates:13}
};
function reviewObmKey(student){const text=[student.program,student.track].join(' ');if(!/OBM|[إا]دارة السلوك التنظيمي/.test(text))return '';const advanced=/المتقدم|الخبير|المستشار|OBM[\s(-]*[EC]/i.test(text),recorded=/مسجل/.test(text);return (advanced?'advanced':'practitioner')+'_'+(recorded?'recorded':'live');}

const reviewBaseModel=reviewModel;
const reviewObmProgramName='إدارة السلوك التنظيمي';
let reviewObmSelectedType='practitioner_live';
function reviewObmModels(){const base=reviewBaseModel(),all=base.filter(p=>/OBM|[إا]دارة السلوك التنظيمي/.test(p.name)).flatMap(p=>p.students);return Object.entries(reviewObmHistory).map(([key,h])=>({name:h.name,obmHistoryKey:key,students:all.filter(s=>reviewObmKey(s)===key),batches:new Map()}));}
reviewModel=function(){const base=reviewBaseModel(),obm=base.filter(p=>/OBM|[إا]دارة السلوك التنظيمي/.test(p.name));return [...base.filter(p=>!obm.includes(p)),{name:reviewObmProgramName,students:obm.flatMap(p=>p.students),batches:new Map(),obm:true}];};
function reviewObmCurrentRows(p){return p.students.filter(s=>{const batch=String(s.batch||'');return /^PRO-/.test(batch)||/السادسة|(?:^|\D)0?6(?:\D|$)/.test(batch);});}
function reviewObmMarkup(p){
 const h=reviewObmHistory[p.obmHistoryKey],total=h.batches.reduce((n,[,v])=>n+v,0),current=h.current?reviewObmCurrentRows(p):[],active=current.filter(s=>performanceStatus(s)==='active');
 const metric=(label,value,sub,tone)=>`<article class="obm-stat ${tone||''}"><span>${label}</span><strong>${value}</strong><small>${sub}</small></article>`;
 return `<section class="obm-overview"><header class="obm-heading"><span>OBM • ${p.obmHistoryKey.endsWith('live')?'مباشر':'مسجل'}</span><h3>${escapeHtml(h.name)}</h3><p>نظرة واضحة على أحجام الدفعات والخريجين</p></header><div class="obm-stats">${metric(h.current?'إجمالي متدربي الدفعات السابقة':'إجمالي متدربي الدفعات',total,h.batches.length+' دفعات معتمدة','obm-stat-blue')}${metric('إجمالي الخريجين',h.graduates===null?'غير محدد':h.graduates,h.graduates===null?'لم يُزوّد عدد الخريجين لهذا النوع':'جزء من الإجمالي، وليس عددًا إضافيًا','obm-stat-green')}${h.current?metric('الفعالون حاليًا · الدفعة السادسة',active.length,'من حسابات الدفعة الحالية','obm-stat-purple'):h.active!==undefined?metric('الفعالون حاليًا',h.active,'الإجمالي '+total+' − الخريجون '+h.graduates,'obm-stat-purple'):''}</div><div class="obm-section-title"><h3>تفاصيل الدفعات</h3><span>مقارنة بين الدفعات • ليست مقارنة شهرية</span></div><div class="obm-cohorts">${h.batches.map(([name,n,graduates],i)=>`<article class="obm-cohort"><div class="obm-cohort-head"><span>دفعة ${i+1}</span><small>${h.current?'مكتملة':'إحصاء معتمد'}</small></div><h4>${escapeHtml(name)}</h4><div class="obm-cohort-number">${n}<span>متدرب</span></div>${h.current?'<footer>خريجو البرنامج</footer>':graduates!==undefined?`<footer>الخريجون: ${graduates}</footer>`:'<footer>إجمالي المسجلين في الدفعة</footer>'}</article>`).join('')}${h.current?`<article class="obm-cohort obm-cohort-current"><div class="obm-cohort-head"><span>دفعة 6</span><small>الدفعة الحالية</small></div><h4>الدفعة السادسة</h4><div class="obm-cohort-number">${current.length}<span>متدرب بالحسابات الحالية</span></div><footer>${active.length} فعال حاليًا <button ${reviewAction('طلاب الدفعة السادسة',reviewRecords(current))}>عرض الحسابات ←</button></footer></article>`:''}</div><p class="or-note">الأعداد التاريخية معتمدة من الإدارة ولا تغيّر حسابات الطلاب. ${h.current?'إجمالي 144 يخص الدفعات الخمس السابقة فقط؛ السادسة تُعرض منفصلة.':''}${p.obmHistoryKey==='practitioner_recorded'?'عدد الخريجين 97 من إجمالي 246؛ لم تُصنّف بقية الحالات تلقائيًا كفعالين.':''}</p></section>`;
}
const reviewObmBaseRender=performanceRender;
performanceRender=function(){
 if(operationalReview.program!==reviewObmProgramName)return reviewObmBaseRender();
 const host=document.getElementById('performanceContent');if(!host||currentUser?.role!=='admin')return;
 operationalReview.requests=[];operationalReview.drawer=null;
 const model=reviewModel(),types=reviewObmModels(),p=types.find(p=>p.obmHistoryKey===reviewObmSelectedType)||types[0];
 host.innerHTML=`<div class="or-dashboard" dir="rtl"><header class="or-header"><div><span class="or-eyebrow">الأداء والتقدم • إدارة السلوك التنظيمي</span><h2>الدفعات والخريجون</h2><p>أحجام الدفعات، الخريجون، والمتدربون الفعالون</p></div></header><nav class="or-program-tabs" aria-label="برامج المراجعة"><button data-review-program="">ملخص الإدارة</button>${model.map(item=>`<button data-review-program="${escapeHtml(item.name)}" aria-pressed="${item.name===reviewObmProgramName}">${escapeHtml(item.name)}</button>`).join('')}</nav><nav class="obm-type-tabs" aria-label="أنواع إدارة السلوك التنظيمي">${types.map(item=>`<button data-obm-type="${item.obmHistoryKey}" aria-pressed="${item.obmHistoryKey===p.obmHistoryKey}">${escapeHtml(item.name.replace('إدارة السلوك التنظيمي ',''))}</button>`).join('')}</nav>${reviewObmMarkup(p)}<div id="orDrawer"></div></div>`;
 host.querySelectorAll('[data-review-program]').forEach(b=>b.onclick=()=>{operationalReview.program=b.dataset.reviewProgram;performanceState.semester='';performanceRender();});
 host.querySelectorAll('[data-obm-type]').forEach(b=>b.onclick=()=>{reviewObmSelectedType=b.dataset.obmType;performanceRender();host.querySelector('[data-obm-type][aria-pressed=true]')?.focus();});
 host.querySelectorAll('[data-review-drill]').forEach(b=>b.onclick=()=>reviewOpenDrawer(Number(b.dataset.reviewDrill)));
};
