/* Aggregate history supplied by administration. It never changes student records. */
const reviewObmHistory={
 practitioner_live:{name:'إدارة السلوك التنظيمي (الممارس) المباشر',batches:[['الدفعة الأولى',24],['الدفعة الثانية',21],['الدفعة الثالثة',12],['الدفعة الرابعة',58],['الدفعة الخامسة',29]],graduates:144,current:true},
 advanced_live:{name:'إدارة السلوك التنظيمي (المتقدم) المباشر',batches:[['الدفعة الأولى',11],['الدفعة الثانية',24]],graduates:13,active:22},
 practitioner_recorded:{name:'إدارة السلوك التنظيمي (الممارس) المسجل',batches:[['الدفعة الأولى · آيات + روزان',39],['الدفعة الثانية · د. ماني',27],['الدفعة الثالثة · مصعب',202]],graduates:97},
 advanced_recorded:{name:'إدارة السلوك التنظيمي (المتقدم) المسجل',batches:[['الدفعة الأولى',12],['الدفعة الثانية',1]],graduates:null}
};
function reviewObmKey(student){const text=[student.program,student.track].join(' ');if(!/OBM|[إا]دارة السلوك التنظيمي/.test(text))return '';const advanced=/المتقدم|الخبير|المستشار|OBM[\s(-]*[EC]/i.test(text),recorded=/مسجل/.test(text);return (advanced?'advanced':'practitioner')+'_'+(recorded?'recorded':'live');}
const reviewBaseModel=reviewModel;
reviewModel=function(){const base=reviewBaseModel(),obm=base.filter(p=>/OBM|[إا]دارة السلوك التنظيمي/.test(p.name)),all=obm.flatMap(p=>p.students);return [...base.filter(p=>!obm.includes(p)),...Object.entries(reviewObmHistory).map(([key,history])=>{const rows=all.filter(s=>reviewObmKey(s)===key),batches=new Map();rows.forEach(s=>{const id=s.batch||'';if(!batches.has(id))batches.set(id,{program:history.name,batch:id,students:[]});batches.get(id).students.push(s);});return {name:history.name,students:rows,batches,obmHistoryKey:key};})];};
function reviewObmCurrentRows(p){return p.students.filter(s=>{const batch=String(s.batch||'');return /^PRO-/.test(batch)||/السادسة|(?:^|\D)0?6(?:\D|$)/.test(batch);});}
function reviewObmMarkup(p){const h=reviewObmHistory[p.obmHistoryKey];if(!h)return '';const total=h.batches.reduce((n,[,value])=>n+value,0),current=h.current?reviewObmCurrentRows(p):[],active=current.filter(s=>performanceStatus(s)==='active'),max=Math.max(...h.batches.map(([,n])=>n),current.length,1);return `<section class="or-panel"><div class="or-section-heading"><h3>الدفعات والخريجون</h3><span>إحصاءات معتمدة من الإدارة · مستقلة عن شهر المراجعة</span></div><div class="or-stage-flow"><div><strong>${total}</strong><span>${h.current?'إجمالي الدفعات الخمس السابقة':'إجمالي الدفعات'}</span></div><div><strong>${h.graduates===null?'غير محدد':h.graduates}</strong><span>الخريجون</span></div>${h.active!==undefined?`<div><strong>${h.active}</strong><span>الفعالون · ${total} − ${h.graduates}</span></div>`:''}${h.current?`<button ${reviewAction('الدفعة السادسة · الفعالون',reviewRecords(active))}><strong>${active.length}</strong><span>الدفعة السادسة · فعالون حاليًا</span></button>`:''}</div><div class="or-table-wrap"><table><thead><tr><th>الدفعة</th><th>عدد المتدربين</th><th>المصدر / الحالة</th></tr></thead><tbody>${h.batches.map(([name,n])=>`<tr><th>${escapeHtml(name)}</th><td><strong>${n}</strong>${performanceBar('',n,max)}</td><td>${h.current?'خريجون':'إحصاء الدفعة المعتمد'}</td></tr>`).join('')}${h.current?`<tr><th>الدفعة السادسة</th><td>${reviewCount('طلاب الدفعة السادسة',reviewRecords(current))}</td><td>من الحسابات الحالية · ${active.length} فعال${current.length?'':' · لا توجد سجلات مرتبطة بالدفعة السادسة محملة'}</td></tr>`:''}</tbody><tfoot><tr><th>${h.current?'إجمالي الدفعات السابقة فقط':'إجمالي الدفعات'}</th><th>${total}</th><td>دون جمع الخريجين مرة أخرى</td></tr></tfoot></table></div><p class="or-note">الأعداد التاريخية إجماليات إدارية، وليست حسابات طلاب جديدة أو تغييرات على حالاتهم.${h.graduates===null?' لم يُحدد عدد الخريجين للمسجل المتقدم.':''}${p.obmHistoryKey==='practitioner_recorded'?' الخريجون 97 من إجمالي 268؛ البقية لا تُصنّف تلقائيًا كفعالين دون التحقق من حالاتهم.':''}</p></section>`;}
const reviewBaseBatchTable=reviewBatchTable;
reviewBatchTable=function(p){return reviewObmMarkup(p)+reviewBaseBatchTable(p);};
