/* Private financial data is fetched only after authenticated authorization. */
const revenueState={data:null,mode:'month',period:'',category:'',family:'',channel:'',segment:'',presentation:false,preview:null,busy:false};
const rvEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rvMoney=v=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const rvNum=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(v);
const rvAllowed=()=>['admin','finance'].includes(currentUser?.role);
const rvAdmin=()=>currentUser?.role==='admin';
// Display-only grouping. Ambiguous services are never guessed into live/recorded.
function rvChannel(category){return /مسجل|مسجلة/.test(category)?'recorded':/مباشر|مباشرة/.test(category)?'live':/مقاعد/.test(category)?'seats':'other';}
const rvChannels=[['live','المباشر'],['recorded','المسجل'],['seats','المقاعد'],['other','الخدمات والأنواع غير المحددة']];

function rvVisible(r){return !/التأهيل|العلاج بالمنزل/.test(r.family||r.baseCategory||'');}
function rvSegment(r){
 if(/OBM/.test(r.family||'')){const text=(r.product||'')+' '+r.baseCategory;const p=/OBM[\\s-]*P|مستوى الممارس/i.test(text),advanced=/OBM[\\s(-]*[EC]|OBME|الخبير|المستشار/i.test(text);return p&&advanced?'مسار يحتاج مراجعة':p?'الممارس P':advanced?'المتقدم E/C':'مسار غير محدد في المصدر';}
 if(/الإشراف والاستشارات/.test(r.family||''))return /مقاعد/.test(r.baseCategory)?'مقاعد':/تقييم الكفاءة/.test(r.baseCategory)?'تقييم كفاءة':/استشارات/.test(r.baseCategory)?'استشارات':'إشراف';
 if(/الدورات والتعليم/.test(r.family||''))return '';
 return '';
}
function rvSegmentOptions(){return [...new Set((revenueState.data?.periods||[]).flatMap(p=>p.rows).filter(r=>rvVisible(r)&&r.state==='included'&&r.family===revenueState.family).map(rvSegment).filter(Boolean))].sort();}
function rvDisplayLabel(r){const segment=rvSegment(r);return segment?segment+' • '+r.baseCategory:r.baseCategory;}

function rvType(category){if(revenueState.family==='الدورات والتعليم المستمر')return category;if(revenueState.family==='الإشراف والاستشارات')return /مقاعد/.test(category)?'seats':/تقييم الكفاءة/.test(category)?'competency':/استشارات/.test(category)?'consulting':'supervision';return rvChannel(category);}
function rvTypes(){if(revenueState.family==='الدورات والتعليم المستمر')return [...new Set((revenueState.data?.periods||[]).flatMap(p=>p.rows).filter(r=>r.state==='included'&&r.family===revenueState.family).map(r=>r.baseCategory))].sort().map(c=>[c,c]);return revenueState.family==='الإشراف والاستشارات'?[['seats','مقاعد'],['supervision','إشراف'],['competency','تقييم كفاءة'],['consulting','استشارات']]:rvChannels;}
function rvRows(months){return (revenueState.data?.periods||[]).filter(p=>months.includes(p.month)).flatMap(p=>p.rows).filter(r=>rvVisible(r)&&(!revenueState.segment||rvSegment(r)===revenueState.segment)&&(!revenueState.category||r.baseCategory===revenueState.category)&&(!revenueState.family||r.family===revenueState.family)&&(!revenueState.channel||rvType(r.baseCategory)===revenueState.channel));}
function rvMonths(){return SulukeraRevenue.selectedMonths(revenueState.period,revenueState.mode);}
function rvCatalog(){return [...new Set((revenueState.data?.periods||[]).flatMap(p=>p.rows).filter(r=>rvVisible(r)&&r.state==='included'&&(!revenueState.segment||rvSegment(r)===revenueState.segment)&&(!revenueState.family||r.family===revenueState.family)&&(!revenueState.channel||rvType(r.baseCategory)===revenueState.channel)).map(r=>r.baseCategory))].sort();}
function rvGoal(category=revenueState.category){
 if(revenueState.segment)return {sales:null,collections:null,source:'لم يُحدد هدف مستقل لهذا المسار أو البرنامج؛ لا نوزّع أهداف التصنيف بالتخمين'};
 const d=revenueState.data,manual=d.goals[revenueState.period+'|'+category];if(manual&&(!!category))return {...manual,source:'هدف مخصص لهذا النطاق'};
 if(revenueState.mode!=='quarter')return {sales:null,collections:null,source:'لم يُحدد هدف لهذا النطاق'};
 const targets=d.quarterTargets.filter(t=>rvVisible({family:SulukeraRevenue.family(t.category)})&&t.period===revenueState.period&&(!category||t.category===category)&&(!revenueState.family||SulukeraRevenue.family(t.category)===revenueState.family)&&(!revenueState.channel||rvType(t.category)===revenueState.channel));
 return {sales:targets.some(t=>t.kind==='sale')?targets.filter(t=>t.kind==='sale').reduce((n,t)=>n+t.amount,0):null,collections:targets.some(t=>t.kind==='collection')?targets.filter(t=>t.kind==='collection').reduce((n,t)=>n+t.amount,0):null,source:'هدف ربعي من ملف المنتجات؛ لا يُقسّم تلقائيًا على الأشهر'};
}
async function renderRevenue(force=false){
 const host=document.getElementById('revenueContent');if(!host)return;if(!rvAllowed()){host.innerHTML='';revenueState.data=null;return;}
 host.innerHTML='<div class="rv-loading">جارٍ تحميل بيانات الإيرادات…</div>';
 try{if(force||!revenueState.data)revenueState.data=await secureAdminExamRequest('/admin/revenue');if(!rvAllowed())return;
 if(!revenueState.period)revenueState.period=revenueState.data.periods.at(-1)?.month||new Date().toISOString().slice(0,7);rvRender();
 }catch(e){revenueState.data=null;host.innerHTML=`<div class="rv-error"><h3>تعذر تحميل البيانات المالية</h3><p>لم تُعرض أرقام صفرية بدل البيانات المفقودة. تحققي من الاتصال وصلاحية الجلسة.</p><button class="rv-btn" onclick="renderRevenue(true)">إعادة المحاولة</button></div>`;console.error('Revenue load failed',e);}
}
function rvFilter(key,value){if(!rvAllowed())return;revenueState[key]=value;if(key==='family'){revenueState.category='';revenueState.channel='';revenueState.segment='';}if(key==='segment')revenueState.category='';if(key==='channel')revenueState.category='';if(key==='mode'){const y=revenueState.period.slice(0,4),m=revenueState.period.includes('-Q')?(Number(revenueState.period.slice(-1))-1)*3+1:Number(revenueState.period.slice(5,7))||1;revenueState.period=value==='year'?y:value==='quarter'?y+'-Q'+Math.ceil(m/3):y+'-'+String(m).padStart(2,'0');}rvRender();}
function rvProgramTabs(){const all=(revenueState.data?.periods||[]).filter(p=>rvMonths().includes(p.month)).flatMap(p=>p.rows).filter(rvVisible),families=[...new Set(revenueState.data.periods.flatMap(p=>p.rows).filter(r=>rvVisible(r)&&r.state==='included').map(r=>r.family))];return `<nav class="rv-programs" aria-label="البرامج"><div class="rv-tabs" role="tablist" aria-label="اختيار البرنامج">${['',...families].map((f,i)=>{const total=SulukeraRevenue.summarize(all.filter(r=>!f||r.family===f)).total;return `<button class="rv-program-tab ${f===revenueState.family?'selected':''}" role="tab" aria-selected="${f===revenueState.family}" data-rv-family="${rvEsc(f)}"><span class="rv-tab-icon">${['◈','◉','▥','◇','⌂','✦'][i%6]}</span><span>${rvEsc(f||'جميع البرامج')}<small>${rvMoney(total)} ر.س</small></span></button>`;}).join('')}</div><div class="rv-channel-tabs" role="tablist" aria-label="نوع التقديم">${[['','كل الأنواع'],...rvTypes()].map(([k,t])=>`<button class="rv-channel-tab ${revenueState.channel===k?'selected':''}" role="tab" aria-selected="${revenueState.channel===k}" data-rv-channel="${rvEsc(k)}">${t}</button>`).join('')}<span class="rv-tab-hint">الرسوم والجداول تتحدث مع اختيارك</span></div>${rvSegmentOptions().length?`<div class="rv-segment-picker"><label>${/OBM/.test(revenueState.family)?'مسار الرخصة':/الإشراف/.test(revenueState.family)?'نوع الخدمة':'البرنامج / الدورة'}<select onchange="rvFilter('segment',this.value)"><option value="">جميع المسارات والبرامج</option>${rvOptions(rvSegmentOptions(),revenueState.segment)}</select></label></div>`:''}</nav>`;}
async function rvPresentation(){if(!rvAllowed())return;const host=document.getElementById('page-revenue')||document.getElementById('revenueContent');if(document.fullscreenElement){await document.exitFullscreen();return;}revenueState.presentation=!revenueState.presentation;host.classList.toggle('rv-presenting',revenueState.presentation);if(revenueState.presentation&&host.requestFullscreen)try{await host.requestFullscreen();}catch{}rvRender();}
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement){revenueState.presentation=false;document.getElementById('page-revenue')?.classList.remove('rv-presenting');document.getElementById('revenueContent')?.classList.remove('rv-presenting');if(rvAllowed()&&revenueState.data)rvRender();}});
function rvOptions(values,current){return values.map(v=>`<option value="${rvEsc(v)}" ${v===current?'selected':''}>${rvEsc(v)}</option>`).join('');}
function rvLegend(){return '<div class="rv-legend"><span><i class="rv-blue"></i>المبيعات</span><span><i class="rv-green"></i>التحصيل</span></div>';}
function rvChartLabel(label){return String(label).replace(/شهادة تحليل السلوك التطبيقي/g,'ABA').replace(/أخصائي تحليل سلوك تطبيقي ABAT 40 ساعة/g,'ABAT 40h').replace(/برامج وخدمات التأهيل والعلاج بالمنزل/g,'التأهيل بالمنزل').replace(/إدارة السلوك التنظيمي/g,'إدارة السلوك').replace(/ورشة انتقائية الطعام - استراتيجيات عملية للتقييم والتدخل/g,'ورشة انتقائية الطعام');}
function rvChart(title,labels,series,{nullLabel='لم يُستورد',wide=false}={}){
 const width=Math.max(wide?1000:520,labels.length*104+110),negative=series.some(s=>s.values.some(v=>v<0)),height=negative?450:360,pad=80,usable=width-pad-24,baseline=negative?225:270;
 const rawMax=Math.max(1,...series.flatMap(s=>s.values).filter(v=>v!==null).map(Math.abs)),unit=10**Math.floor(Math.log10(rawMax)),max=Math.ceil(rawMax/unit)*unit,scale=negative?145:180;
 let marks='';for(let tick=0;tick<=4;tick++){const value=max*tick/4,y=baseline-value/max*scale;marks+=`<line x1="${pad}" y1="${y}" x2="${width-20}" y2="${y}" stroke="#e2e9f6" stroke-dasharray="${tick?'4 5':'0'}"/><text x="${pad-12}" y="${y+4}" text-anchor="end" class="rv-axis-value">${rvNum(value)}</text>`;}
 const step=usable/Math.max(labels.length,1),bw=Math.min(54,step/(series.length+1.4)),gap=Math.min(12,bw*.25);
 labels.forEach((label,i)=>{const center=pad+(i+.5)*step,groupWidth=series.length*bw+(series.length-1)*gap,values=series.map(s=>s.values[i]),peak=baseline-Math.max(0,...values.filter(v=>v!==null))/max*scale;
  series.forEach((s,j)=>{const v=s.values[i],x=center-groupWidth/2+j*(bw+gap);if(v===null)return;const h=Math.abs(v)/max*scale,y=v<0?baseline:baseline-h;
   marks+=`<rect class="rv-column" x="${x}" y="${y}" width="${bw}" height="${Math.max(v===0?0:h,0)}" rx="6" fill="${s.color}"><title>${rvEsc(label+' — '+s.name+': '+rvMoney(v)+' ر.س')}</title></rect><text x="${center}" y="${v<0?baseline+h+20+j*18:peak-16-(series.length-j-1)*19}" text-anchor="middle" fill="${s.color}" class="rv-column-amount" data-amount="${v}">${rvMoney(v)}</text>`;
  });
  const words=rvChartLabel(label).split(' '),wrapped=[];let line='';for(const word of words){if((line+' '+word).trim().length>22&&line){wrapped.push(line);line=word;}else line=(line+' '+word).trim();}if(line)wrapped.push(line);
  const labelY=negative?405:300;marks+=`<text x="${center}" y="${labelY}" text-anchor="middle" class="rv-column-label"><title>${rvEsc(label)}</title>${wrapped.slice(0,3).map((l,j)=>`<tspan x="${center}" dy="${j?18:0}">${rvEsc(j===2&&wrapped.length>3?l+'…':l)}</tspan>`).join('')}</text>`;
  if(values.every(v=>v===null))marks+=`<text x="${center}" y="${baseline-14}" text-anchor="middle" class="rv-svg-value">—</text>`;
 });
 const legend=`<div class="rv-legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${rvEsc(s.name)}</span>`).join('')}</div>`;
 return `<section class="rv-panel rv-chart ${wide?'rv-chart-wide':''}"><div class="rv-section-head"><div><h3>${rvEsc(title)}</h3><p>ريال سعودي • المبلغ ظاهر مباشرة فوق الأعمدة${title.startsWith('مسار')&&title.endsWith('2026')?' • يناير–مارس: لم يفصل المصدر التحصيل عن البيع':''}</p></div>${legend}</div><div class="rv-chart-scroll"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${rvEsc(title)}" direction="ltr" style="min-width:${labels.length>6?Math.round(width*.7):0}px">${marks}</svg></div><details class="rv-chart-data"><summary>عرض قيم الرسم</summary><div class="rv-scroll"><table><thead><tr><th>الفترة / المنتج</th>${series.map(s=>`<th>${rvEsc(s.name)}</th>`).join('')}</tr></thead><tbody>${labels.map((l,i)=>`<tr><td>${rvEsc(l)}</td>${series.map(s=>`<td>${s.values[i]===null?nullLabel:rvMoney(s.values[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></section>`;
}
function rvProductTables(groups,missing){
 const channels=revenueState.channel?rvTypes().filter(([key])=>key===revenueState.channel):rvTypes().filter(([key])=>['live','recorded'].includes(key)||groups.some(g=>rvType(g.category)===key));
 return '<div class="rv-split-tables">'+channels.map(([key,title])=>{const list=groups.filter(g=>rvType(g.category)===key),total=list.reduce((s,g)=>({sales:s.sales+g.sales,collections:s.collections+g.collections,count:s.count+g.count}),{sales:0,collections:0,count:0});
 return `<section class="rv-panel rv-product-section rv-type-${key}" data-rv-table="${key}"><div class="rv-section-head"><div><span class="rv-section-kicker">${key==='live'?'LIVE':key==='recorded'?'RECORDED':key==='seats'?'SEATS':'OTHER'}</span><h3>بيانات ${title}</h3><p>${total.count} عملية • جدول مستقل ضمن البرنامج والفترة المختارين</p></div><div class="rv-section-total"><small>المبيعات + التحصيل</small><strong>${rvMoney(total.sales+total.collections)} <em>ر.س</em></strong></div></div><div class="rv-scroll"><table><thead><tr><th>المنتج</th><th>المبيعات</th><th>التحصيل</th><th>الإجمالي</th><th>الهدف / الإنجاز</th><th>العمليات</th><th>التفاصيل</th></tr></thead><tbody>${list.map(g=>`<tr><td><b>${rvEsc(g.label||g.category)}</b></td><td class="rv-sales-text">${rvMoney(g.sales)}</td><td class="rv-green-text">${rvMoney(g.collections)}</td><td><b>${rvMoney(g.total)}</b></td><td>مبيعات: ${g.goal.sales===null?'غير محدد':rvMoney(g.goal.sales)}<small>تحصيل: ${g.goal.collections===null?'غير محدد':rvMoney(g.goal.collections)}${g.goal.sales>0&&!missing.length?' • إنجاز المبيعات '+rvNum(g.sales/g.goal.sales*100)+'%':''}</small></td><td>${g.count}</td><td><button class="rv-btn" data-rv-label="${rvEsc(g.label||g.category)}">عرض العمليات</button></td></tr>`).join('')||'<tr><td colspan="7" class="rv-table-empty">لا توجد عمليات محتسبة لهذا النوع في الفترة المختارة.</td></tr>'}</tbody><tfoot><tr><th>إجمالي ${title}</th><th>${rvMoney(total.sales)}</th><th>${rvMoney(total.collections)}</th><th>${rvMoney(total.sales+total.collections)}</th><th>—</th><th>${total.count}</th><th></th></tr></tfoot></table></div></section>`;
 }).join('')+'</div>';
}
function rvRender(){
 if(!rvAllowed()||!revenueState.data)return;const host=document.getElementById('revenueContent'),d=revenueState.data,rows=rvRows(rvMonths()),s=SulukeraRevenue.summarize(rows),goal=rvGoal(),periods=d.periods.filter(p=>rvMonths().includes(p.month)),catalog=rvCatalog();
 const years=[...new Set(d.periods.map(p=>p.month.slice(0,4)))].sort().reverse(),periodOptions=revenueState.mode==='month'?d.periods.map(p=>p.month).reverse():revenueState.mode==='quarter'?years.flatMap(y=>[1,2,3,4].map(q=>y+'-Q'+q)):years;
 const groups=[...new Set(rows.filter(r=>r.state==='included').map(rvDisplayLabel))].map(label=>{const matching=rows.filter(r=>rvDisplayLabel(r)===label),category=matching[0].baseCategory;return {category,label,...SulukeraRevenue.summarize(matching),goal:rvSegment(matching[0])?{sales:null,collections:null}:rvGoal(category)};}).filter(g=>g.count).sort((a,b)=>b.total-a.total);
 const latest=periods.map(p=>p.asOf).filter(Boolean).sort().at(-1),missing=rvMonths().filter(m=>!d.periods.some(p=>p.month===m));
 const allYear=Array.from({length:12},(_,i)=>revenueState.period.slice(0,4)+'-'+String(i+1).padStart(2,'0')),trend=allYear.map(m=>d.periods.some(p=>p.month===m)?SulukeraRevenue.summarize(rvRows([m])):null);
 const typeKeys=rvTypes().filter(([key])=>revenueState.channel?key===revenueState.channel:['live','recorded'].includes(key)||rows.some(r=>r.state==='included'&&rvType(r.baseCategory)===key)),typeTotals=typeKeys.map(([key])=>SulukeraRevenue.summarize(rows.filter(r=>rvType(r.baseCategory)===key)));
 const series=values=>[{name:'المبيعات',color:'#2453ef',values:values.map(v=>v?.sales??null)},{name:'التحصيل',color:'#0ba88b',values:values.map(v=>v?.collections??null)}];
 host.innerHTML=`<div class="rv-wrap"><header class="rv-hero"><div><span class="rv-eyebrow">رؤية مالية • أرقام موثّقة</span><h2>الإيرادات وأهداف المنتجات</h2><p>المبيعات والتحصيل، كلٌّ على حدة. من العملية الأصلية إلى مؤشرات الأداء.</p></div><div class="rv-hero-actions"><button class="rv-btn rv-display-button" onclick="rvPresentation()">${revenueState.presentation?'إنهاء العرض':'وضع الاجتماع ⛶'}</button><button class="rv-btn rv-edit-action" onclick="renderRevenue(true)">تحديث البيانات</button>${rvAdmin()?'<label class="rv-btn rv-primary rv-edit-action">استيراد تحديث Excel<input type="file" accept=".xlsx" onchange="rvImport(this)" hidden></label>':''}</div></header>
 ${rvProgramTabs()}
 <section class="rv-panel rv-filters rv-meeting-filters"><label>الفترة<select onchange="rvFilter('mode',this.value)">${[['month','شهري'],['quarter','ربع سنوي'],['year','سنوي']].map(([v,t])=>`<option value="${v}" ${revenueState.mode===v?'selected':''}>${t}</option>`).join('')}</select></label><label>اختيار الفترة<select onchange="rvFilter('period',this.value)">${rvOptions(periodOptions,revenueState.period)}</select></label><label>المنتج / تصنيف الملف<select onchange="rvFilter('category',this.value)"><option value="">جميع المنتجات</option>${rvOptions(catalog,revenueState.category)}</select></label></section>
 <div class="rv-scope-strip"><div><span>عرض البرنامج</span><h3>${rvEsc(revenueState.family||'جميع البرامج')} ${revenueState.segment?'— '+rvEsc(revenueState.segment):''} <small>• ${rvEsc(rvTypes().find(([k])=>k===revenueState.channel)?.[1]||'كل الأنواع')}</small></h3></div><bdi dir="ltr">${rvEsc(revenueState.period)}</bdi><button class="rv-btn" onclick="rvDetails('included')">جميع العمليات</button></div>
 <div class="rv-source-line"><span>آخر تحديث المصدر <bdi dir="ltr">${rvEsc(latest||'لا توجد بيانات مستوردة للفترة')}</bdi> • ${rvNum(s.count)} عملية محتسبة • المبالغ بالريال وبدون ضريبة القيمة المضافة</span><span>المتجر + الرسوم الإدارية + تحصيل - أخرى + التأهيل والعلاج: مستبعدة من العرض</span></div>
 ${missing.length?`<div class="rv-notice">لم تُستورد بيانات: ${missing.join('، ')}. إجماليات الفترة تشمل الأشهر المستوردة فقط؛ الأشهر المفقودة ليست صفرًا.</div>`:''}
 ${rvMonths().some(m=>['2026-01','2026-02','2026-03'].includes(m))?'<div class="rv-notice">تنبيه المصدر: أوراق يناير–مارس لا تفصل التحصيل عن البيع. تُعرض مبالغها حسب تصنيفها الأصلي؛ صفر التحصيل هنا لا يعني عدم وجود تحصيل فعلي. ملخص يناير يعيد توزيع جزء من ABAT على تقييم الكفاءة؛ هنا نحتفظ بتصنيف العمليات الأصلية.</div>':''}
 <section class="rv-metrics"><article class="rv-metric rv-sales"><span>المبيعات</span><strong>${rvMoney(s.sales)}</strong><small>عمليات البيع حسب تصنيف الملف</small></article><article class="rv-metric rv-collections"><span>التحصيل</span><strong>${rvMoney(s.collections)}</strong><small>دفعات التحصيل المصنفة في الملف</small></article><article class="rv-metric"><span>إجمالي المبيعات والتحصيل</span><strong>${rvMoney(s.total)}</strong><small>مجموع العمليتين؛ ليس إيرادًا محاسبيًا معترفًا به</small></article><article class="rv-metric rv-goal"><span>إنجاز هدف المبيعات</span><strong>${goal.sales>0&&!missing.length?rvNum(s.sales/goal.sales*100)+'%':'—'}</strong><small>${goal.sales===null?'لم يحدد هدف مطابق':missing.length?'يتطلب اكتمال بيانات الفترة':'الهدف: '+rvMoney(goal.sales)}</small></article></section>
 <div class="rv-charts">${rvChart('مسار المبيعات والتحصيل • '+revenueState.period.slice(0,4),allYear.map(m=>m.slice(5)),series(trend),{wide:true})}${rvChart((revenueState.channel?rvTypes().find(([k])=>k===revenueState.channel)?.[1]:revenueState.family==='الدورات والتعليم المستمر'?'تصنيفات الدورات': 'المباشر والمسجل')+' • المبيعات والتحصيل',typeKeys.map(([,title])=>title),series(typeTotals))}${rvChart('الأداء مقابل الهدف',['المبيعات','التحصيل'],[{name:'الفعلي',color:'#2453ef',values:[s.sales,s.collections]},{name:'الهدف المطابق',color:'#9473e8',values:[goal.sales,goal.collections]}],{nullLabel:'غير محدد'})}${rvChart('مساهمة المنتجات'+(groups.length>10?' • أعلى 10 منتجات':'')+' • '+(revenueState.family||'جميع البرامج'),groups.slice(0,10).map(g=>g.label||g.category),series(groups.slice(0,10)),{wide:true})}</div>
 <section class="rv-panel"><div class="rv-section-head"><div><h3>أهداف هذا النطاق</h3><p>${rvEsc(goal.source)}</p></div>${rvAdmin()?'<button class="rv-btn" onclick="rvEditGoal()">ضبط الهدف</button>':''}</div><div class="rv-goal-stats"><span>هدف المبيعات <b>${goal.sales===null?'غير محدد':rvMoney(goal.sales)}</b></span><span>هدف التحصيل <b>${goal.collections===null?'غير محدد':rvMoney(goal.collections)}</b></span><span>إنجاز التحصيل <b>${goal.collections>0&&!missing.length?rvNum(s.collections/goal.collections*100)+'%':'—'}</b></span></div><p class="rv-muted">الهدف الشهري في أوراق الملف يشمل بنودًا مستبعدة؛ لا نستخدمه لحساب إنجاز هذا النطاق. أهداف المنتجات الأصلية ربع سنوية. الهدف الصفري أو غير المحدد لا ينتج نسبة إنجاز.</p></section>
 ${rvProductTables(groups,missing)}
 <section class="rv-panel rv-audit"><div class="rv-section-head"><div><h3>المطابقة ومراجعة المصدر</h3><p>لا حذف للصفوف المتشابهة، ولا إدخال للصفوف الناقصة في النتائج.</p></div></div><div class="rv-audit-actions"><button class="rv-btn" onclick="rvDetails('excluded')">العمليات المستبعدة • ${rvMoney(s.excluded)} ر.س</button><button class="rv-btn" onclick="rvDetails('review')">صفوف تحتاج مراجعة • ${s.review}</button><button class="rv-btn" onclick="rvDetails('notes')">ملاحظات البيانات</button></div><details><summary>مراجع الاستيراد وأهداف الملف الأصلية</summary><p class="rv-muted">التحصيل يُحدد من تصنيف «تحصيل» في الملف، وليس من اسم المنتج أو التخمين. التصنيفات المتقاربة تظل منفصلة إذا لم يثبت تطابقها.</p>${periods.map(p=>`<p>${rvEsc(p.sheet)} • آخر تحديث ${rvEsc(p.asOf)} • هدف الملف قبل الاستبعادات: ${p.sourceTarget===null?'غير محدد':rvMoney(p.sourceTarget)}</p>`).join('')}${d.imports.map(i=>`<p>${rvEsc(i.filename)} — استيراد ${rvEsc(i.imported_at?.slice(0,10))}</p>`).join('')}</details></section></div>`;
 host.querySelectorAll('[data-rv-label]').forEach(b=>b.onclick=()=>rvDetails('included','',b.dataset.rvLabel));
 host.querySelectorAll('[data-rv-category]').forEach(b=>b.onclick=()=>rvDetails('included',b.dataset.rvCategory));
 host.querySelectorAll('[data-rv-family],[data-rv-channel]').forEach(b=>{b.onclick=()=>{const key=b.hasAttribute('data-rv-family')?'family':'channel';rvFilter(key,key==='family'?b.dataset.rvFamily:b.dataset.rvChannel);host.querySelector(`.rv-${key==='family'?'program':'channel'}-tab.selected`)?.focus({preventScroll:true});};});
 host.querySelectorAll('[role=tablist]').forEach(list=>{list.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...list.querySelectorAll('[role=tab]')],index=buttons.indexOf(document.activeElement);if(index<0)return;e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowLeft'?1:-1)+buttons.length)%buttons.length].click();};});
}
function rvClose(){document.getElementById('rvOverlay')?.remove();document.body.style.overflow='';}
function rvModal(title,body){rvClose();const overlay=document.createElement('div');overlay.id='rvOverlay';overlay.className='rv-overlay';overlay.innerHTML=`<section class="rv-modal" role="dialog" aria-modal="true" aria-label="${rvEsc(title)}"><header><h3>${rvEsc(title)}</h3><button class="rv-btn" onclick="rvClose()" aria-label="إغلاق">✕</button></header>${body}</section>`;overlay.onclick=e=>{if(e.target===overlay)rvClose();};document.body.append(overlay);overlay.querySelector('button')?.focus();document.body.style.overflow='hidden';}
document.addEventListener('keydown',e=>{if(e.key==='Escape')rvClose();});
function rvDetails(state,category='',label=''){
 if(!rvAllowed())return;const rows=rvRows(rvMonths()).filter(r=>(state==='notes'?r.note:r.state===state)&&(!category||r.baseCategory===category)&&(!label||rvDisplayLabel(r)===label));let page=0;
 rvModal(label||category||({included:'العمليات المحتسبة',excluded:'العمليات المستبعدة',review:'صفوف تحتاج مراجعة',notes:'ملاحظات المصدر'})[state],'<input id="rvSearch" class="rv-search" placeholder="بحث باسم المنتج، المرجع أو التاريخ" aria-label="بحث في العمليات"><div id="rvDetailRows"></div>');
 const draw=()=>{const q=document.getElementById('rvSearch').value.trim().toLowerCase(),filtered=rows.filter(r=>[r.product,r.category,r.reference,r.date].join(' ').toLowerCase().includes(q)),max=Math.max(1,Math.ceil(filtered.length/30));page=Math.min(page,max-1);document.getElementById('rvDetailRows').innerHTML=`<p class="rv-muted">${filtered.length} عملية • مجموع المبالغ ${rvMoney(filtered.reduce((n,r)=>n+r.net,0))} ر.س</p><div class="rv-scroll"><table><thead><tr><th>التاريخ / المرجع</th><th>المنتج والتصنيف</th><th>المبلغ بدون الضريبة</th><th>المصدر والملاحظات</th></tr></thead><tbody>${filtered.slice(page*30,page*30+30).map(r=>`<tr><td>${rvEsc(r.date||'غير محدد')}<small>${rvEsc(r.reference)}</small></td><td><b>${rvEsc(r.product)}</b><small>${rvEsc(r.category)} • ${rvEsc(r.platform)}</small></td><td>${rvMoney(r.net)}</td><td>${rvEsc(r.sourceSheet)} • الصف ${rvEsc(r.sourceRow)}<small>${rvEsc(r.reason||r.note||'')}</small></td></tr>`).join('')||'<tr><td colspan="4">لا توجد عمليات مطابقة.</td></tr>'}</tbody></table></div><div class="rv-pager"><button id="rvPrev" class="rv-btn" ${page===0?'disabled':''}>السابق</button><span>${page+1} / ${max}</span><button id="rvNext" class="rv-btn" ${page+1===max?'disabled':''}>التالي</button></div>`;document.getElementById('rvPrev').onclick=()=>{page--;draw();};document.getElementById('rvNext').onclick=()=>{page++;draw();};};document.getElementById('rvSearch').oninput=()=>{page=0;draw();};draw();
}
function rvEditGoal(){if(revenueState.segment){alert('اختاري تصنيف الملف الكامل لتعديل هدفه؛ لا يوجد هدف مستقل محفوظ لهذا المسار.');return;}if(!rvAdmin()||(revenueState.family||revenueState.channel)&&!revenueState.category){showToast('اختاري منتجًا محددًا أو جميع البرامج وكل الأنواع لضبط هدف واضح النطاق');return;}const goal=rvGoal();rvModal('ضبط هدف • '+revenueState.period+' • '+(revenueState.category||'جميع المنتجات'),`<p>هدف مستقل لهذا النطاق، بدون البنود المستبعدة. اتركي الحقل فارغًا إن لم يحدد هدف؛ لا تُوزّع الأهداف الربع سنوية تلقائيًا.</p><label>هدف المبيعات (ر.س)<input id="rvSalesGoal" type="number" min="0" step="0.01" value="${goal.sales??''}"></label><label>هدف التحصيل (ر.س)<input id="rvCollectionGoal" type="number" min="0" step="0.01" value="${goal.collections??''}"></label><p id="rvGoalError" role="alert"></p><button id="rvGoalSave" class="rv-btn rv-primary" onclick="rvSaveGoal()">حفظ الهدف</button>`);}
async function rvSaveGoal(){if(!rvAdmin())return;const b={period:revenueState.period,category:revenueState.category};for(const [k,id] of [['sales','rvSalesGoal'],['collections','rvCollectionGoal']]){const v=document.getElementById(id).value;b[k]=v===''?null:Number(v);if(b[k]!==null&&(!Number.isFinite(b[k])||b[k]<0)){document.getElementById('rvGoalError').textContent='الهدف يجب أن يكون مبلغًا غير سالب';return;}}const button=document.getElementById('rvGoalSave');button.disabled=true;try{await secureAdminExamRequest('/admin/revenue/goal',{method:'POST',body:JSON.stringify(b)});rvClose();await renderRevenue(true);showToast('تم حفظ الهدف مع سجل التعديل');}catch(e){document.getElementById('rvGoalError').textContent='تعذر حفظ الهدف؛ لم يتغير الهدف السابق';button.disabled=false;}}
function rvExcelDay(serial,date1904=false){const d=XLSX.SSF.parse_date_code(serial,{date1904});return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null;}
async function rvImport(input){if(!rvAdmin()||!input.files[0])return;const file=input.files[0];try{if(!window.XLSX)throw Error('مكتبة Excel غير متاحة');if(file.size>20*1024*1024)throw Error('حجم الملف أكبر من 20MB');const buffer=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join(''),book=XLSX.read(buffer,{type:'array',cellDates:false}),sheets={};for(const name of book.SheetNames){if(!/^(\S+) (\d{2}|\d{4})$/.test(name)&&name!=='أهداف مبيعات المنتجات')continue;sheets[name]=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:null,blankrows:true}).map((r,i)=>r.map((v,j)=>(j===1||(i===1&&j===3))&&typeof v==='number'&&v>30000?rvExcelDay(v,!!book.Workbook?.WBProps?.date1904):v));}revenueState.preview=SulukeraRevenue.parse({filename:file.name,sourceHash:hash,sheets});const p=revenueState.preview,s=SulukeraRevenue.summarize(p.periods.flatMap(p=>p.rows));if(!p.periods.length)throw Error('لا توجد أوراق شهرية مطابقة لقالب المصدر');rvModal('مراجعة استيراد الإيرادات',`<p>الملف: ${rvEsc(file.name)} • سنة الاستيراد: ${p.year}</p><p class="rv-notice">الاعتماد يستبدل بيانات الأشهر الموجودة في الملف فقط، ويحافظ على باقي الأشهر والأهداف المخصصة. رفع الملف نفسه مرة أخرى لا يكرر العمليات.</p><div class="rv-goal-stats"><span>مبيعات <b>${rvMoney(s.sales)}</b></span><span>تحصيل <b>${rvMoney(s.collections)}</b></span><span>تحتاج مراجعة <b>${s.review}</b></span><span>المبالغ المستبعدة <b>${rvMoney(s.excluded)}</b></span></div><div class="rv-scroll"><table><thead><tr><th>الشهر</th><th>عمليات محتسبة</th><th>الإجمالي</th><th>الإجراء</th></tr></thead><tbody>${p.periods.map(m=>{const a=SulukeraRevenue.summarize(m.rows);return `<tr><td>${m.month}</td><td>${a.count}</td><td>${rvMoney(a.total)}</td><td>${revenueState.data.periods.some(x=>x.month===m.month)?'استبدال الشهر':'إضافة شهر'}</td></tr>`;}).join('')}</tbody></table></div><details><summary>ملاحظات الملف (${p.issues.length})</summary>${p.issues.map(i=>`<p>${rvEsc(i.sheet)} ${i.row?'• '+i.row:''} — ${rvEsc(i.reason)}</p>`).join('')}</details><p id="rvImportError" role="alert"></p><button id="rvImportConfirm" class="rv-btn rv-primary" onclick="rvConfirmImport()">اعتماد الاستيراد</button>`);}catch(e){showToast('تعذر قراءة الملف: '+e.message);}finally{input.value='';}}
async function rvConfirmImport(){if(!rvAdmin()||!revenueState.preview||revenueState.busy)return;revenueState.busy=true;document.getElementById('rvImportConfirm').disabled=true;try{const result=await secureAdminExamRequest('/admin/revenue/import',{method:'POST',body:JSON.stringify(revenueState.preview)});revenueState.preview=null;rvClose();await renderRevenue(true);showToast(result.duplicate?'هذا الملف مستورد مسبقًا؛ لم تتكرر العمليات':'تم اعتماد بيانات الملف');}catch(e){document.getElementById('rvImportError').textContent='تعذر اعتماد الملف؛ لم تُستبدل البيانات السابقة. '+e.message;document.getElementById('rvImportConfirm').disabled=false;}finally{revenueState.busy=false;}}
