/* Private financial data is fetched only after authenticated authorization. */
const revenueState={data:null,mode:'month',period:'',category:'',family:'',preview:null,busy:false};
const rvEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rvMoney=v=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const rvNum=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(v);
const rvAllowed=()=>['admin','finance'].includes(currentUser?.role);
const rvAdmin=()=>currentUser?.role==='admin';
function rvRows(months){return (revenueState.data?.periods||[]).filter(p=>months.includes(p.month)).flatMap(p=>p.rows).filter(r=>(!revenueState.category||r.baseCategory===revenueState.category)&&(!revenueState.family||r.family===revenueState.family));}
function rvMonths(){return SulukeraRevenue.selectedMonths(revenueState.period,revenueState.mode);}
function rvCatalog(){return [...new Set((revenueState.data?.periods||[]).flatMap(p=>p.rows).filter(r=>r.state==='included'&&(!revenueState.family||r.family===revenueState.family)).map(r=>r.baseCategory))].sort();}
function rvGoal(category=revenueState.category){
 const d=revenueState.data,manual=d.goals[revenueState.period+'|'+category];if(manual&&(!revenueState.family||category))return {...manual,source:'هدف مخصص لهذا النطاق'};
 if(revenueState.mode!=='quarter')return {sales:null,collections:null,source:'لم يُحدد هدف لهذا النطاق'};
 const targets=d.quarterTargets.filter(t=>t.period===revenueState.period&&(!category||t.category===category)&&(!revenueState.family||SulukeraRevenue.family(t.category)===revenueState.family));
 return {sales:targets.some(t=>t.kind==='sale')?targets.filter(t=>t.kind==='sale').reduce((n,t)=>n+t.amount,0):null,collections:targets.some(t=>t.kind==='collection')?targets.filter(t=>t.kind==='collection').reduce((n,t)=>n+t.amount,0):null,source:'هدف ربعي من ملف المنتجات؛ لا يُقسّم تلقائيًا على الأشهر'};
}
async function renderRevenue(force=false){
 const host=document.getElementById('revenueContent');if(!host)return;if(!rvAllowed()){host.innerHTML='';revenueState.data=null;return;}
 host.innerHTML='<div class="rv-loading">جارٍ تحميل بيانات الإيرادات…</div>';
 try{if(force||!revenueState.data)revenueState.data=await secureAdminExamRequest('/admin/revenue');if(!rvAllowed())return;
 if(!revenueState.period)revenueState.period=revenueState.data.periods.at(-1)?.month||new Date().toISOString().slice(0,7);rvRender();
 }catch(e){revenueState.data=null;host.innerHTML=`<div class="rv-error"><h3>تعذر تحميل البيانات المالية</h3><p>لم تُعرض أرقام صفرية بدل البيانات المفقودة. تحققي من الاتصال وصلاحية الجلسة.</p><button class="rv-btn" onclick="renderRevenue(true)">إعادة المحاولة</button></div>`;console.error('Revenue load failed',e);}
}
function rvFilter(key,value){if(!rvAllowed())return;revenueState[key]=value;if(key==='family')revenueState.category='';if(key==='mode'){const y=revenueState.period.slice(0,4),m=revenueState.period.includes('-Q')?(Number(revenueState.period.slice(-1))-1)*3+1:Number(revenueState.period.slice(5,7))||1;revenueState.period=value==='year'?y:value==='quarter'?y+'-Q'+Math.ceil(m/3):y+'-'+String(m).padStart(2,'0');}rvRender();}
function rvOptions(values,current){return values.map(v=>`<option value="${rvEsc(v)}" ${v===current?'selected':''}>${rvEsc(v)}</option>`).join('');}
function rvLegend(){return '<div class="rv-legend"><span><i class="rv-blue"></i>المبيعات</span><span><i class="rv-green"></i>التحصيل</span></div>';}
function rvChart(title,labels,series,{horizontal=false,nullLabel='لم يُستورد'}={}){
 const width=640,rowHeight=42,negative=series.some(s=>s.values.some(v=>v<0)),height=horizontal?Math.max(180,labels.length*rowHeight+28):negative?280:240,pad=horizontal?210:34,usable=width-pad-24;
 const max=Math.max(1,...series.flatMap(s=>s.values).filter(v=>v!==null).map(Math.abs));let marks='';
 if(horizontal){
  const baseline=negative?Math.round(24+(usable-65)/2):24,scale=(usable-65)/(negative?2:1);
  if(negative)marks+=`<line x1="${baseline}" y1="15" x2="${baseline}" y2="${height-10}" stroke="#a1b1cf"/>`;
  labels.forEach((label,i)=>{const y=22+i*rowHeight;marks+=`<text x="630" y="${y+12}" text-anchor="end" class="rv-svg-label"><title>${rvEsc(label)}</title>${rvEsc(label.length>30?label.slice(0,29)+'…':label)}</text>`;
   series.forEach((s,j)=>{const v=s.values[i];if(v===null)return;const w=Math.abs(v)/max*scale,x=v<0?baseline-w:baseline;marks+=`<rect x="${x}" y="${y+j*14}" width="${w}" height="10" rx="4" fill="${s.color}"><title>${rvEsc(label+' — '+s.name+': '+rvMoney(v))}</title></rect><text x="${v<0?x-3:x+w+4}" y="${y+j*14+9}" text-anchor="${v<0?'end':'start'}" class="rv-svg-value">${rvNum(v)}</text>`;});
  });
 }else{
  const step=usable/Math.max(labels.length,1),baseline=negative?135:180,scale=negative?100:150;
  labels.forEach((label,i)=>{const x=pad+i*step;series.forEach((s,j)=>{const v=s.values[i];if(v===null)return;const h=Math.abs(v)/max*scale,bw=Math.max(4,Math.min(22,step/series.length-4));marks+=`<rect x="${x+j*(bw+3)}" y="${v<0?baseline:baseline-h}" width="${bw}" height="${h}" rx="4" fill="${s.color}"><title>${rvEsc(label+' — '+s.name+': '+rvMoney(v))}</title></rect>`;});
   marks+=`<text x="${x+12}" y="${negative?258:202}" text-anchor="middle" class="rv-svg-label">${rvEsc(label)}</text>`;if(series.every(s=>s.values[i]===null))marks+=`<text x="${x+12}" y="${baseline-5}" text-anchor="middle" class="rv-svg-value">—</text>`;
  });
  marks+=`<text x="${pad}" y="16" class="rv-svg-value">${rvNum(max)} ر.س</text><line x1="${pad}" y1="${baseline}" x2="620" y2="${baseline}" stroke="#a1b1cf"/>`;
 }
 return `<section class="rv-panel rv-chart"><div class="rv-section-head"><h3>${rvEsc(title)}</h3>${rvLegend()}</div><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${rvEsc(title)}" direction="ltr">${marks}</svg><details class="rv-chart-data"><summary>عرض قيم الرسم</summary><div class="rv-scroll"><table><thead><tr><th>الفترة / المنتج</th>${series.map(s=>`<th>${s.name}</th>`).join('')}</tr></thead><tbody>${labels.map((l,i)=>`<tr><td>${rvEsc(l)}</td>${series.map(s=>`<td>${s.values[i]===null?nullLabel:rvMoney(s.values[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></section>`;
}
function rvRender(){
 if(!rvAllowed()||!revenueState.data)return;const host=document.getElementById('revenueContent'),d=revenueState.data,rows=rvRows(rvMonths()),s=SulukeraRevenue.summarize(rows),goal=rvGoal(),periods=d.periods.filter(p=>rvMonths().includes(p.month)),catalog=rvCatalog();
 const years=[...new Set(d.periods.map(p=>p.month.slice(0,4)))].sort().reverse(),periodOptions=revenueState.mode==='month'?d.periods.map(p=>p.month).reverse():revenueState.mode==='quarter'?years.flatMap(y=>[1,2,3,4].map(q=>y+'-Q'+q)):years;
 const groups=catalog.map(category=>({category,...SulukeraRevenue.summarize(rows.filter(r=>r.baseCategory===category)),goal:rvGoal(category)})).filter(g=>g.count).sort((a,b)=>b.total-a.total);
 const latest=periods.map(p=>p.asOf).filter(Boolean).sort().at(-1),missing=rvMonths().filter(m=>!d.periods.some(p=>p.month===m));
 const allYear=Array.from({length:12},(_,i)=>revenueState.period.slice(0,4)+'-'+String(i+1).padStart(2,'0')),trend=allYear.map(m=>d.periods.some(p=>p.month===m)?SulukeraRevenue.summarize(rvRows([m])):null);
 const weekLabels=[...new Set(rows.filter(r=>r.state==='included').map(r=>r.week||'بدون أسبوع'))],weeks=weekLabels.map(w=>SulukeraRevenue.summarize(rows.filter(r=>(r.week||'بدون أسبوع')===w)));
 const series=values=>[{name:'المبيعات',color:'#2453ef',values:values.map(v=>v?.sales??null)},{name:'التحصيل',color:'#0ba88b',values:values.map(v=>v?.collections??null)}];
 host.innerHTML=`<div class="rv-wrap"><header class="rv-hero"><div><span class="rv-eyebrow">رؤية مالية • أرقام موثّقة</span><h2>الإيرادات وأهداف المنتجات</h2><p>المبيعات والتحصيل، كلٌّ على حدة. من العملية الأصلية إلى مؤشرات الأداء.</p></div><div class="rv-hero-actions"><button class="rv-btn" onclick="renderRevenue(true)">تحديث البيانات</button>${rvAdmin()?'<label class="rv-btn rv-primary">استيراد تحديث Excel<input type="file" accept=".xlsx" onchange="rvImport(this)" hidden></label>':''}</div></header>
 <section class="rv-panel rv-filters"><label>الفترة<select onchange="rvFilter('mode',this.value)">${[['month','شهري'],['quarter','ربع سنوي'],['year','سنوي']].map(([v,t])=>`<option value="${v}" ${revenueState.mode===v?'selected':''}>${t}</option>`).join('')}</select></label><label>اختيار الفترة<select onchange="rvFilter('period',this.value)">${rvOptions(periodOptions,revenueState.period)}</select></label><label>مجموعة المنتجات<select onchange="rvFilter('family',this.value)"><option value="">جميع المجموعات</option>${rvOptions([...new Set(d.periods.flatMap(p=>p.rows).filter(r=>r.state==='included').map(r=>r.family))].sort(),revenueState.family)}</select></label><label>المنتج / تصنيف الملف<select onchange="rvFilter('category',this.value)"><option value="">جميع المنتجات</option>${rvOptions(catalog,revenueState.category)}</select></label></section>
 <div class="rv-source-line"><span>آخر تحديث المصدر <bdi dir="ltr">${rvEsc(latest||'لا توجد بيانات مستوردة للفترة')}</bdi> • ${rvNum(s.count)} عملية محتسبة • المبالغ بالريال وبدون ضريبة القيمة المضافة</span><span>المتجر + الرسوم الإدارية + تحصيل - أخرى: مستبعدة</span></div>
 ${missing.length?`<div class="rv-notice">لم تُستورد بيانات: ${missing.join('، ')}. إجماليات الفترة تشمل الأشهر المستوردة فقط؛ الأشهر المفقودة ليست صفرًا.</div>`:''}
 ${rvMonths().some(m=>['2026-01','2026-02','2026-03'].includes(m))?'<div class="rv-notice">تنبيه المصدر: أوراق يناير–مارس لا تفصل التحصيل عن البيع. تُعرض مبالغها حسب تصنيفها الأصلي؛ صفر التحصيل هنا لا يعني عدم وجود تحصيل فعلي. ملخص يناير يعيد توزيع جزء من ABAT على تقييم الكفاءة؛ هنا نحتفظ بتصنيف العمليات الأصلية.</div>':''}
 <section class="rv-metrics"><article class="rv-metric rv-sales"><span>المبيعات</span><strong>${rvMoney(s.sales)}</strong><small>عمليات البيع حسب تصنيف الملف</small></article><article class="rv-metric rv-collections"><span>التحصيل</span><strong>${rvMoney(s.collections)}</strong><small>دفعات التحصيل المصنفة في الملف</small></article><article class="rv-metric"><span>إجمالي المبيعات والتحصيل</span><strong>${rvMoney(s.total)}</strong><small>مجموع العمليتين؛ ليس إيرادًا محاسبيًا معترفًا به</small></article><article class="rv-metric rv-goal"><span>إنجاز هدف المبيعات</span><strong>${goal.sales>0&&!missing.length?rvNum(s.sales/goal.sales*100)+'%':'—'}</strong><small>${goal.sales===null?'لم يحدد هدف مطابق':missing.length?'يتطلب اكتمال بيانات الفترة':'الهدف: '+rvMoney(goal.sales)}</small></article></section>
 <div class="rv-charts">${rvChart('مسار المبيعات والتحصيل • '+revenueState.period.slice(0,4),allYear.map(m=>m.slice(5)),series(trend))}${rvChart('مساهمة المنتجات',groups.slice(0,10).map(g=>g.category),series(groups.slice(0,10)),{horizontal:true})}${rvChart('الأداء مقابل الهدف',['المبيعات','التحصيل'],[{name:'الفعلي',color:'#2453ef',values:[s.sales,s.collections]},{name:'الهدف المطابق',color:'#9473e8',values:[goal.sales,goal.collections]}],{nullLabel:'غير محدد'})}${rvChart('التوزيع حسب أسابيع الملف',weekLabels,series(weeks),{horizontal:true})}</div>
 <section class="rv-panel"><div class="rv-section-head"><div><h3>أهداف هذا النطاق</h3><p>${rvEsc(goal.source)}</p></div>${rvAdmin()?'<button class="rv-btn" onclick="rvEditGoal()">ضبط الهدف</button>':''}</div><div class="rv-goal-stats"><span>هدف المبيعات <b>${goal.sales===null?'غير محدد':rvMoney(goal.sales)}</b></span><span>هدف التحصيل <b>${goal.collections===null?'غير محدد':rvMoney(goal.collections)}</b></span><span>إنجاز التحصيل <b>${goal.collections>0&&!missing.length?rvNum(s.collections/goal.collections*100)+'%':'—'}</b></span></div><p class="rv-muted">الهدف الشهري في أوراق الملف يشمل بنودًا مستبعدة؛ لا نستخدمه لحساب إنجاز هذا النطاق. أهداف المنتجات الأصلية ربع سنوية. الهدف الصفري أو غير المحدد لا ينتج نسبة إنجاز.</p></section>
 <section class="rv-panel"><div class="rv-section-head"><div><h3>أداء كل منتج</h3><p>فصل البيع والتحصيل مع الاحتفاظ بتصنيف كل عملية ومصدرها.</p></div><button class="rv-btn" onclick="rvDetails('included')">جميع العمليات</button></div><div class="rv-scroll"><table><thead><tr><th>المنتج</th><th>المبيعات</th><th>التحصيل</th><th>الإجمالي</th><th>الهدف / الإنجاز</th><th>عدد العمليات</th><th>التفاصيل</th></tr></thead><tbody>${groups.map((g,i)=>`<tr><td><b>${rvEsc(g.category)}</b><small>${rvEsc(SulukeraRevenue.family(g.category))}</small></td><td class="rv-sales-text">${rvMoney(g.sales)}</td><td class="rv-green-text">${rvMoney(g.collections)}</td><td><b>${rvMoney(g.total)}</b></td><td>مبيعات: ${g.goal.sales===null?'غير محدد':rvMoney(g.goal.sales)}<small>تحصيل: ${g.goal.collections===null?'غير محدد':rvMoney(g.goal.collections)}${g.goal.sales>0&&!missing.length?' • إنجاز المبيعات '+rvNum(g.sales/g.goal.sales*100)+'%':''}</small></td><td>${rvNum(g.count)}</td><td><button class="rv-btn" data-rv-category="${rvEsc(g.category)}">عرض العمليات</button></td></tr>`).join('')||'<tr><td colspan="7">لا توجد عمليات محتسبة في هذا النطاق.</td></tr>'}</tbody><tfoot><tr><th>الإجمالي</th><th>${rvMoney(s.sales)}</th><th>${rvMoney(s.collections)}</th><th>${rvMoney(s.total)}</th><th>—</th><th>${s.count}</th><th></th></tr></tfoot></table></div></section>
 <section class="rv-panel rv-audit"><div class="rv-section-head"><div><h3>المطابقة ومراجعة المصدر</h3><p>لا حذف للصفوف المتشابهة، ولا إدخال للصفوف الناقصة في النتائج.</p></div></div><div class="rv-audit-actions"><button class="rv-btn" onclick="rvDetails('excluded')">العمليات المستبعدة • ${rvMoney(s.excluded)} ر.س</button><button class="rv-btn" onclick="rvDetails('review')">صفوف تحتاج مراجعة • ${s.review}</button><button class="rv-btn" onclick="rvDetails('notes')">ملاحظات البيانات</button></div><details><summary>مراجع الاستيراد وأهداف الملف الأصلية</summary><p class="rv-muted">التحصيل يُحدد من تصنيف «تحصيل» في الملف، وليس من اسم المنتج أو التخمين. التصنيفات المتقاربة تظل منفصلة إذا لم يثبت تطابقها.</p>${periods.map(p=>`<p>${rvEsc(p.sheet)} • آخر تحديث ${rvEsc(p.asOf)} • هدف الملف قبل الاستبعادات: ${p.sourceTarget===null?'غير محدد':rvMoney(p.sourceTarget)}</p>`).join('')}${d.imports.map(i=>`<p>${rvEsc(i.filename)} — استيراد ${rvEsc(i.imported_at?.slice(0,10))}</p>`).join('')}</details></section></div>`;
 host.querySelectorAll('[data-rv-category]').forEach(b=>b.onclick=()=>rvDetails('included',b.dataset.rvCategory));
 // The target chart has its own actual/target legend, not the sales/collection legend.
 const targetLegend=host.querySelectorAll('.rv-chart .rv-legend')[2];if(targetLegend)targetLegend.innerHTML='<span><i class="rv-blue"></i>الفعلي</span><span><i style="background:#9473e8"></i>الهدف المطابق</span>';
}
function rvClose(){document.getElementById('rvOverlay')?.remove();document.body.style.overflow='';}
function rvModal(title,body){rvClose();const overlay=document.createElement('div');overlay.id='rvOverlay';overlay.className='rv-overlay';overlay.innerHTML=`<section class="rv-modal" role="dialog" aria-modal="true" aria-label="${rvEsc(title)}"><header><h3>${rvEsc(title)}</h3><button class="rv-btn" onclick="rvClose()" aria-label="إغلاق">✕</button></header>${body}</section>`;overlay.onclick=e=>{if(e.target===overlay)rvClose();};document.body.append(overlay);overlay.querySelector('button')?.focus();document.body.style.overflow='hidden';}
document.addEventListener('keydown',e=>{if(e.key==='Escape')rvClose();});
function rvDetails(state,category=''){
 if(!rvAllowed())return;const rows=rvRows(rvMonths()).filter(r=>(state==='notes'?r.note:r.state===state)&&(!category||r.baseCategory===category));let page=0;
 rvModal(category||({included:'العمليات المحتسبة',excluded:'العمليات المستبعدة',review:'صفوف تحتاج مراجعة',notes:'ملاحظات المصدر'})[state],'<input id="rvSearch" class="rv-search" placeholder="بحث باسم المنتج، المرجع أو التاريخ" aria-label="بحث في العمليات"><div id="rvDetailRows"></div>');
 const draw=()=>{const q=document.getElementById('rvSearch').value.trim().toLowerCase(),filtered=rows.filter(r=>[r.product,r.category,r.reference,r.date].join(' ').toLowerCase().includes(q)),max=Math.max(1,Math.ceil(filtered.length/30));page=Math.min(page,max-1);document.getElementById('rvDetailRows').innerHTML=`<p class="rv-muted">${filtered.length} عملية • مجموع المبالغ ${rvMoney(filtered.reduce((n,r)=>n+r.net,0))} ر.س</p><div class="rv-scroll"><table><thead><tr><th>التاريخ / المرجع</th><th>المنتج والتصنيف</th><th>المبلغ بدون الضريبة</th><th>المصدر والملاحظات</th></tr></thead><tbody>${filtered.slice(page*30,page*30+30).map(r=>`<tr><td>${rvEsc(r.date||'غير محدد')}<small>${rvEsc(r.reference)}</small></td><td><b>${rvEsc(r.product)}</b><small>${rvEsc(r.category)} • ${rvEsc(r.platform)}</small></td><td>${rvMoney(r.net)}</td><td>${rvEsc(r.sourceSheet)} • الصف ${rvEsc(r.sourceRow)}<small>${rvEsc(r.reason||r.note||'')}</small></td></tr>`).join('')||'<tr><td colspan="4">لا توجد عمليات مطابقة.</td></tr>'}</tbody></table></div><div class="rv-pager"><button id="rvPrev" class="rv-btn" ${page===0?'disabled':''}>السابق</button><span>${page+1} / ${max}</span><button id="rvNext" class="rv-btn" ${page+1===max?'disabled':''}>التالي</button></div>`;document.getElementById('rvPrev').onclick=()=>{page--;draw();};document.getElementById('rvNext').onclick=()=>{page++;draw();};};document.getElementById('rvSearch').oninput=()=>{page=0;draw();};draw();
}
function rvEditGoal(){if(!rvAdmin()||revenueState.family&&!revenueState.category){showToast('اختاري منتجًا محددًا أو جميع المجموعات لضبط هدف واضح النطاق');return;}const goal=rvGoal();rvModal('ضبط هدف • '+revenueState.period+' • '+(revenueState.category||'جميع المنتجات'),`<p>هدف مستقل لهذا النطاق، بدون البنود المستبعدة. اتركي الحقل فارغًا إن لم يحدد هدف؛ لا تُوزّع الأهداف الربع سنوية تلقائيًا.</p><label>هدف المبيعات (ر.س)<input id="rvSalesGoal" type="number" min="0" step="0.01" value="${goal.sales??''}"></label><label>هدف التحصيل (ر.س)<input id="rvCollectionGoal" type="number" min="0" step="0.01" value="${goal.collections??''}"></label><p id="rvGoalError" role="alert"></p><button id="rvGoalSave" class="rv-btn rv-primary" onclick="rvSaveGoal()">حفظ الهدف</button>`);}
async function rvSaveGoal(){if(!rvAdmin())return;const b={period:revenueState.period,category:revenueState.category};for(const [k,id] of [['sales','rvSalesGoal'],['collections','rvCollectionGoal']]){const v=document.getElementById(id).value;b[k]=v===''?null:Number(v);if(b[k]!==null&&(!Number.isFinite(b[k])||b[k]<0)){document.getElementById('rvGoalError').textContent='الهدف يجب أن يكون مبلغًا غير سالب';return;}}const button=document.getElementById('rvGoalSave');button.disabled=true;try{await secureAdminExamRequest('/admin/revenue/goal',{method:'POST',body:JSON.stringify(b)});rvClose();await renderRevenue(true);showToast('تم حفظ الهدف مع سجل التعديل');}catch(e){document.getElementById('rvGoalError').textContent='تعذر حفظ الهدف؛ لم يتغير الهدف السابق';button.disabled=false;}}
function rvExcelDay(serial,date1904=false){const d=XLSX.SSF.parse_date_code(serial,{date1904});return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null;}
async function rvImport(input){if(!rvAdmin()||!input.files[0])return;const file=input.files[0];try{if(!window.XLSX)throw Error('مكتبة Excel غير متاحة');if(file.size>20*1024*1024)throw Error('حجم الملف أكبر من 20MB');const buffer=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join(''),book=XLSX.read(buffer,{type:'array',cellDates:false}),sheets={};for(const name of book.SheetNames){if(!/^(\S+) (\d{2}|\d{4})$/.test(name)&&name!=='أهداف مبيعات المنتجات')continue;sheets[name]=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:null,blankrows:true}).map((r,i)=>r.map((v,j)=>(j===1||(i===1&&j===3))&&typeof v==='number'&&v>30000?rvExcelDay(v,!!book.Workbook?.WBProps?.date1904):v));}revenueState.preview=SulukeraRevenue.parse({filename:file.name,sourceHash:hash,sheets});const p=revenueState.preview,s=SulukeraRevenue.summarize(p.periods.flatMap(p=>p.rows));if(!p.periods.length)throw Error('لا توجد أوراق شهرية مطابقة لقالب المصدر');rvModal('مراجعة استيراد الإيرادات',`<p>الملف: ${rvEsc(file.name)} • سنة الاستيراد: ${p.year}</p><p class="rv-notice">الاعتماد يستبدل بيانات الأشهر الموجودة في الملف فقط، ويحافظ على باقي الأشهر والأهداف المخصصة. رفع الملف نفسه مرة أخرى لا يكرر العمليات.</p><div class="rv-goal-stats"><span>مبيعات <b>${rvMoney(s.sales)}</b></span><span>تحصيل <b>${rvMoney(s.collections)}</b></span><span>تحتاج مراجعة <b>${s.review}</b></span><span>المبالغ المستبعدة <b>${rvMoney(s.excluded)}</b></span></div><div class="rv-scroll"><table><thead><tr><th>الشهر</th><th>عمليات محتسبة</th><th>الإجمالي</th><th>الإجراء</th></tr></thead><tbody>${p.periods.map(m=>{const a=SulukeraRevenue.summarize(m.rows);return `<tr><td>${m.month}</td><td>${a.count}</td><td>${rvMoney(a.total)}</td><td>${revenueState.data.periods.some(x=>x.month===m.month)?'استبدال الشهر':'إضافة شهر'}</td></tr>`;}).join('')}</tbody></table></div><details><summary>ملاحظات الملف (${p.issues.length})</summary>${p.issues.map(i=>`<p>${rvEsc(i.sheet)} ${i.row?'• '+i.row:''} — ${rvEsc(i.reason)}</p>`).join('')}</details><p id="rvImportError" role="alert"></p><button id="rvImportConfirm" class="rv-btn rv-primary" onclick="rvConfirmImport()">اعتماد الاستيراد</button>`);}catch(e){showToast('تعذر قراءة الملف: '+e.message);}finally{input.value='';}}
async function rvConfirmImport(){if(!rvAdmin()||!revenueState.preview||revenueState.busy)return;revenueState.busy=true;document.getElementById('rvImportConfirm').disabled=true;try{const result=await secureAdminExamRequest('/admin/revenue/import',{method:'POST',body:JSON.stringify(revenueState.preview)});revenueState.preview=null;rvClose();await renderRevenue(true);showToast(result.duplicate?'هذا الملف مستورد مسبقًا؛ لم تتكرر العمليات':'تم اعتماد بيانات الملف');}catch(e){document.getElementById('rvImportError').textContent='تعذر اعتماد الملف؛ لم تُستبدل البيانات السابقة. '+e.message;document.getElementById('rvImportConfirm').disabled=false;}finally{revenueState.busy=false;}}
