import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleLecturerSurvey} from './src/lecturer-survey.js';
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('./lecturer-survey.sql',import.meta.url),'utf8'));return {sql,DB:{prepare(q){const statement=sql.prepare(q);return {bind(...args){return {first:async()=>statement.get(...args)||null,all:async()=>({results:statement.all(...args)}),run:async()=>statement.run(...args)};}};}}};}
const auth=(role,uid='lecturer1')=>({uid,token:'fixture',profile:{role,name:'محاضر تجريبي',username:uid}}),deps={firebaseRead:async()=>({lecturer1:{role:'lecturer',name:'أول'},lecturer2:{role:'lecturer',name:'ثاني'},student1:{role:'student'}})};
function payload(value=5){return {campaignId:SulukeraLecturerSurvey.campaign.id,responses:{...Object.fromEntries(SulukeraLecturerSurvey.ratings.map(([key])=>[key,value])),problem:'no',stages:['none'],recommendation:10,...Object.fromEntries(SulukeraLecturerSurvey.texts.map(([key])=>[key,'إجابة تجريبية']))}};}
const req=(path,body)=>new Request('https://test.invalid'+path,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}),call=(env,role,path,body,uid)=>handleLecturerSurvey(req(path,body),env,auth(role,uid),path,deps);
test('lecturer gate, server-derived identity, one immutable response across retry/concurrent submissions',async()=>{const env=fixture();assert.equal((await call(env,'lecturer','/lecturer/satisfaction')).data.completed,false);const p=payload();p.responses.uid='someone-else';await Promise.all([call(env,'lecturer','/lecturer/satisfaction',p),call(env,'lecturer','/lecturer/satisfaction',payload(1))]);assert.equal(env.sql.prepare('SELECT count(*) n FROM lecturer_survey_responses').get().n,1);assert.equal(env.sql.prepare('SELECT lecturer_uid FROM lecturer_survey_responses').get().lecturer_uid,'lecturer1');const before=env.sql.prepare('SELECT responses_json FROM lecturer_survey_responses').get().responses_json;await call(env,'lecturer','/lecturer/satisfaction',payload(2));assert.equal(env.sql.prepare('SELECT responses_json FROM lecturer_survey_responses').get().responses_json,before);const result=(await call(env,'lecturer','/lecturer/satisfaction')).data;assert.equal(result.completed,true);assert.equal(result.records,undefined);});
test('admin-only analytics; all other roles rejected before reading response data',async()=>{const env=fixture();for(const role of ['lecturer','student','finance'])await assert.rejects(call(env,role,'/admin/lecturer-satisfaction'),e=>e.status===403);for(const role of ['admin','student','finance'])await assert.rejects(call(env,role,'/lecturer/satisfaction'),e=>e.status===403);await call(env,'lecturer','/lecturer/satisfaction',payload());let d=(await call(env,'admin','/admin/lecturer-satisfaction')).data;assert.equal(d.overallPercent,100);assert.equal(d.responseRate,50);assert.equal(d.pending.length,1);assert.equal(d.eligibleCount,2);assert.equal(d.recommendationAverage,10);assert.deepEqual(d.questions.overall.distribution,[0,0,0,0,1]);});
test('reject incomplete ratings, recommendation and text or contradictory stage selections with no write',async()=>{for(const change of [p=>delete p.responses.overall,p=>p.responses.instructions=6,p=>p.responses.stages=[],p=>p.responses.stages=['none','during'],p=>p.responses.recommendation=0,p=>p.responses.message=' ',p=>p.campaignId='other-term']){const env=fixture(),p=payload();change(p);await assert.rejects(call(env,'lecturer','/lecturer/satisfaction',p),e=>e.status===400);assert.equal(env.sql.prepare('SELECT count(*) n FROM lecturer_survey_responses').get().n,0);}});
test('empty results are unavailable; ratings use matching denominator and recommendation stays separate',async()=>{const env=fixture();let d=(await call(env,'admin','/admin/lecturer-satisfaction')).data;assert.equal(d.overallPercent,null);assert.equal(d.recommendationAverage,null);assert.equal(d.responseRate,0);await call(env,'lecturer','/lecturer/satisfaction',payload(1));const p=payload(5);p.responses.problem='yes';p.responses.stages=['start','during'];p.responses.recommendation=2;await call(env,'lecturer','/lecturer/satisfaction',p,'lecturer2');d=(await call(env,'admin','/admin/lecturer-satisfaction')).data;assert.equal(d.overallPercent,60);assert.equal(d.dimensionsPercent,60);assert.equal(d.recommendationAverage,6);assert.equal(d.problemCount,1);assert.equal(d.responseRate,100);assert.deepEqual(d.questions.overall.distribution,[1,0,0,0,1]);assert.equal(d.stages.find(s=>s.id==='during').count,1);});

test('Afnan is exempt for this campaign, cannot submit, and is excluded from participation and stored-response analytics',async()=>{const env=fixture(),uid='Rd1O695bgWdbu3xk1AUAoIYmJPk2',account={uid,profile:{role:'lecturer',name:'أفنان المبدل',username:'Aalmubaddal'}},path='/lecturer/satisfaction';const result=await handleLecturerSurvey(req(path),env,account,path,deps);assert.equal(result.data.exempt,true);assert.equal(result.data.completed,true);await assert.rejects(handleLecturerSurvey(req(path,payload()),env,account,path,deps),e=>e.status===403);env.sql.prepare('INSERT INTO lecturer_survey_responses VALUES (?,?,?,?,?,?)').run(SulukeraLecturerSurvey.campaign.id,uid,'أفنان المبدل','Aalmubaddal',JSON.stringify(payload().responses),new Date().toISOString());const data=(await handleLecturerSurvey(req('/admin/lecturer-satisfaction'),env,auth('admin'),'/admin/lecturer-satisfaction',{firebaseRead:async()=>({...await deps.firebaseRead(),[uid]:account.profile})})).data;assert.equal(data.eligibleCount,2);assert.equal(data.responseCount,0);assert.equal(data.pending.length,2);assert.equal(data.overallPercent,null);assert.equal(env.sql.prepare('SELECT count(*) n FROM lecturer_survey_responses').get().n,1);});
