import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleRevenue} from './src/revenue.js';
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('./revenue.sql',import.meta.url),'utf8'));return {sql,DB:{prepare(q){const statement=sql.prepare(q);return {all:async()=>({results:statement.all()}),first:async()=>statement.get()||null,bind(...args){return {first:async()=>statement.get(...args)||null,all:async()=>({results:statement.all(...args)}),run:()=>statement.run(...args)};}};},async batch(items){sql.exec('BEGIN');try{const result=items.map(i=>i.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}}};}
const auth=role=>({uid:'test-'+role,profile:{role}});
function payload(hash='a'.repeat(64),month='2026-10'){return {sourceHash:hash,filename:'fixture.xlsx',quarterTargets:[],issues:[],periods:[{month,asOf:month+'-07',sourceTarget:9000,sheet:'fixture',rows:[{id:'1',date:month+'-04',category:'منتج تجريبي',baseCategory:'tampered',family:'tampered',product:'Product <script>',net:100,gross:115,kind:'sale',state:'included',sourceSheet:'fixture',sourceRow:17},{id:'2',date:month+'-04',category:'منتج تجريبي - تحصيل',product:'installment',net:50,kind:'sale',state:'included'},{id:'3',date:month+'-04',category:'تحصيل - أخرى',product:'excluded',net:500,kind:'sale',state:'included'}]}]};}
const request=(path,data)=>new Request('https://example.test'+path,{method:data?'POST':'GET',...(data?{body:JSON.stringify(data)}:{})});
test('financial data is not readable by lecturer/student and finance cannot mutate',async()=>{const env=fixture();for(const role of ['student','lecturer'])await assert.rejects(handleRevenue(request('/admin/revenue'),env,auth(role),'/admin/revenue'),e=>e.status===403);await assert.rejects(handleRevenue(request('/admin/revenue/import',payload()),env,auth('finance'),'/admin/revenue/import'),e=>e.status===403);assert.deepEqual((await handleRevenue(request('/admin/revenue'),env,auth('finance'),'/admin/revenue')).data.periods,[]);});
test('atomic import, enforced exclusions and classification, duplicate hash and month replacement isolation',async()=>{const env=fixture();let result=await handleRevenue(request('/admin/revenue/import',payload()),env,auth('admin'),'/admin/revenue/import');assert.equal(result.data.summary.total,150);assert.equal(result.data.summary.excluded,500);let d=(await handleRevenue(request('/admin/revenue'),env,auth('admin'),'/admin/revenue')).data;assert.equal(d.periods[0].rows[1].kind,'collection');assert.equal(d.periods[0].rows[0].baseCategory,'منتج تجريبي');assert.equal(d.periods[0].rows[2].state,'excluded');result=await handleRevenue(request('/admin/revenue/import',payload()),env,auth('admin'),'/admin/revenue/import');assert.equal(result.data.duplicate,true);await handleRevenue(request('/admin/revenue/import',payload('b'.repeat(64),'2026-09')),env,auth('admin'),'/admin/revenue/import');const replacement=payload('c'.repeat(64));replacement.periods[0].rows[0].net=200;await handleRevenue(request('/admin/revenue/import',replacement),env,auth('admin'),'/admin/revenue/import');d=(await handleRevenue(request('/admin/revenue'),env,auth('admin'),'/admin/revenue')).data;assert.equal(d.periods.length,2);assert.equal(d.periods[0].rows[0].net,100);assert.equal(d.periods[1].rows[0].net,200);assert.equal(d.imports.length,3);});
test('reject malformed dates, nonfinite amounts and invalid targets before any write',async()=>{for(const change of [p=>delete p.periods[0].rows[0].date,p=>p.periods[0].rows[0].date='2026-02-30',p=>p.periods[0].rows[0].net=null,p=>p.quarterTargets=[{period:'2026-Q5',category:'x',amount:10,kind:'sale'}]]){const env=fixture(),p=payload();change(p);await assert.rejects(handleRevenue(request('/admin/revenue/import',p),env,auth('admin'),'/admin/revenue/import'));assert.equal(env.sql.prepare('SELECT count(*) n FROM revenue_periods').get().n,0);}});
test('manual goals preserve nullable/zero values and edits have an audit trail',async()=>{const env=fixture(),p={period:'2026-10',category:'',sales:0,collections:null};await handleRevenue(request('/admin/revenue/goal',p),env,auth('admin'),'/admin/revenue/goal');let d=(await handleRevenue(request('/admin/revenue'),env,auth('admin'),'/admin/revenue')).data;assert.deepEqual(d.goals['2026-10|'],{sales:0,collections:null});p.sales=900;await handleRevenue(request('/admin/revenue/goal',p),env,auth('admin'),'/admin/revenue/goal');assert.equal(env.sql.prepare('SELECT count(*) n FROM revenue_goal_audit').get().n,2);});
test('shared parser ignores empty template rows, keeps real duplicate rows, flags missing categories, supports future years',()=>{const rows=Array.from({length:20},()=>[]);rows[15][5]='التصنيف';rows[15][18]='المبيعات بدون الضريبة';for(const index of [16,17]){rows[index][1]='2027-01-04';rows[index][5]='منتج';rows[index][8]='Actual';rows[index][14]='same';rows[index][18]='100.50';}rows[18][1]='2027-01-05';rows[18][18]=80;rows[19][0]=99;rows[19][18]=0;const parsed=SulukeraRevenue.parse({sheets:{'يناير 27':rows,'أهداف مبيعات المنتجات':[[null,'الربع الأول'],[null,'منتج',200]]}});assert.equal(parsed.periods[0].rows.length,3);assert.equal(parsed.periods[0].rows[2].state,'review');assert.equal(parsed.quarterTargets[0].period,'2027-Q1');assert.equal(SulukeraRevenue.summarize(parsed.periods[0].rows).total,201);assert.equal(SulukeraRevenue.day('2026-99-01'),null);assert.equal(SulukeraRevenue.day('2026-02-30'),null);});
