const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync('academic-policy.js','utf8'),ctx);const p=ctx.SulukeraAcademicPolicy;
const qasp={batch:'Q9-28',planType:'QASP-S'},qba={batch:'Q9-28',planType:'QBA'};
assert.equal(p.subjectAllowed(qasp,{semesterNo:5}),false);
assert.equal(p.subjectAllowed(qasp,{courseKey:'course_16'}),false);
assert.equal(p.subjectAllowed(qasp,{semesterNo:4}),true);
assert.equal(p.subjectAllowed(qba,{semesterNo:6}),true);
assert.equal(p.subjectAllowed(qba,{semesterNo:7}),false);
assert.equal(p.subjectAllowed({pkg:'QBA'}, {semesterNo:5}),true);
const terms={last:{batches:['Q9-28'],endDate:'2028-09-24',subjects:['end']}};
assert.equal(p.projectStage(qasp,terms,{end:{semesterNo:4}},{},'2028-10-04'),true);
assert.equal(p.projectStage(qba,terms,{end:{semesterNo:4}},{},'2028-10-04'),false);
assert.equal(p.projectStage(qba,terms,{end:{semesterNo:6}},{},'2028-10-04'),true);
assert.equal(p.projectStage(qba,terms,{end:{semesterNo:6}},{},'2028-09-24'),false);
assert.equal(p.projectStage({...qba,batch:'Q10-28'},terms,{end:{semesterNo:6}},{},'2028-10-04'),false);
const html=fs.readFileSync('student.html','utf8');
const fixture={...ctx,dbData:{students:{a:qasp,b:qba},packages:{},subjects:{fifth:{semesterNo:5,eligiblePlans:['QBA']},sixth:{semesterNo:6},seventh:{semesterNo:7},old:{semesterNo:4}},enrollments:{a:{studentKey:'a',subjectKey:'fifth'},b:{studentKey:'a',subjectKey:'old'},c:{studentKey:'b',subjectKey:'sixth'},d:{studentKey:'b',subjectKey:'seventh'}}},currentUser:null};
vm.createContext(fixture);vm.runInContext(html.slice(html.indexOf('function normalizeBatchName('),html.indexOf('function activeSubjectKeysForBatch('))+html.slice(html.indexOf('function getStudentSubjects('),html.indexOf('function getGrade_data(')),fixture);
assert.deepEqual(Array.from(fixture.getStudentSubjects('a'),s=>s.key),['old']);
assert.deepEqual(Array.from(fixture.getStudentSubjects('b'),s=>s.key),['sixth']);
console.log('PASS: Track limits apply even to direct enrollment; graduation stage is date- and track-based for future cohorts.');
