const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const {chromium}=require('playwright');
const html=fs.readFileSync('index.html','utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1]);
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.setContent('<html dir="rtl"><head><style>'+html.match(/<style>([\s\S]*?)<\/style>/)[1]+'</style></head><body><main id="page-performance"><div id="performanceContent"></div></main></body></html>');await page.addStyleTag({path:'performance.css'});
await page.evaluate(()=>{
Object.assign(window,{currentUser:{role:'admin',username:'admin'},students:[],programsData:[],users:[],subjects:[],grades:{},semestersData:{},enrollmentsData:[],professionalProgramsData:{},professionalEnrollmentsData:{},lecturerProductivityData:{},settings:{gradeFail:80},writes:[]});
window.escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.normalizeBatchName=v=>String(v).trim();window.sameBatchName=(a,b)=>a.trim()===b.trim();window.getLecturerName=id=>id||'—';window.getStudentListClassification=s=>s.planType||'';window.getSubjectSemesterSummary=s=>({name:'الفصل '+s.semesterNo,state:'ongoing',semesterKey:s.semesterKey});window.getLecturerProductivityRecord=(p,u)=>lecturerProductivityData[p]?.[u]||{};window.formatProductivityHours=String;window.calcTotal=g=>g.total;window.isExamEntered=g=>g?.examEntered===true;window.secureAdminExamRequest=async()=>({evaluations:[]});window.fbRef=path=>({update:async payload=>writes.push({path,payload})});
});await page.addScriptTag({path:'performance.js'});await page.evaluate(()=>renderPerformance());assert.equal(await page.locator('#performanceStudents').count(),0);assert.equal(await page.locator('.performance-kpis .insight-card').count(),8);
await page.evaluate(()=>{
programsData=[{name:'ABA',tracks:[{name:'QBA',batches:[{name:'10'}]},{name:'QASP-S',batches:[{name:'10'}]}]},{name:'OBM',tracks:[{name:'ممارس',batches:[{name:'11'}]}]}];
students=[{_fbKey:'a',program:'ABA',track:'QBA',batch:'10',planType:'QBA'},{_fbKey:'b',program:'ABA',track:'QASP-S',batch:'10',planType:'QASP-S'},{_fbKey:'c',program:'ABA',track:'QBA',batch:'10',planType:'QBA'},{_fbKey:'d',program:'ABA',track:'QBA',batch:'10',planType:'QBA'},{_fbKey:'e',program:'OBM',batch:'11',planType:'PROFESSIONAL'}];
subjects=[{_fbKey:'s1',batch:'10',semesterNo:1,students:[0,1,2,3],lecturerUserId:'L'},{_fbKey:'s2',batch:'10',semesterNo:1,students:[0,1,2,3],lecturerUserId:'L'},{_fbKey:'s3',batch:'11',semesterNo:1,students:[4],lecturerUserId:'M'}];
grades={0:{0:{examEntered:true,total:90},1:{examEntered:true,total:50},3:{examEntered:true,total:90}},1:{0:{examEntered:true,total:85},1:{examEntered:true,total:90}},2:{4:{examEntered:true,total:100}}};users=[{name:'محاضر أ',username:'L',role:'lecturer'},{name:'محاضر ب',username:'M',role:'lecturer'}];lecturerProductivityData={'2026-10':{L:{extraHours:7,note:'preserve'}}};subjects.forEach(s=>{s.startDate='2026-08-23';s.endDate='2026-09-24';});performanceState.period='2026-10';performanceRender();
});assert.equal(await page.locator('.performance-batch').count(),2);assert.equal(await page.evaluate(()=>performanceModel()[0].batches.size),1);assert.equal(await page.evaluate(()=>performanceModel()[0].students.length),4);
assert.deepEqual(await page.evaluate(()=>{const r=performanceSemesterResults(performanceModel()[0].batches.values().next().value)[0];return [r.tested,r.passed,r.absent,r.partial,r.rate]}),[3,2,1,1,66.7]);assert.equal(await page.evaluate(()=>performanceSemesterResults(performanceModel()[1].batches.values().next().value).length),0);
await page.evaluate(()=>{subjects.push({_fbKey:'future',batch:'10',semesterNo:2,startDate:'2026-11-01',endDate:'2026-12-01',students:[0,1,2,3]},{_fbKey:'current',batch:'10',semesterNo:3,startDate:'2026-10-04',endDate:'2026-11-05',students:[0,1,2,3]},{_fbKey:'unknown',batch:'10',semesterNo:4,students:[0,1,2,3]});performanceRender();});assert.equal(await page.evaluate(()=>performanceSemesterResults(performanceModel()[0].batches.values().next().value).length),1);assert.match(await page.locator('[aria-label="فصل نسبة النجاح"]').innerText(),/2026-08-23 إلى 2026-09-24/);
await page.evaluate(()=>{students.push({_fbKey:'withdrawn',program:'ABA',batch:'10',planType:'QBA',accountStatus:'withdrawn'});enrollmentsData.push({studentKey:'withdrawn',subjectKey:'s1'});programsData.push({name:'شهادة إدارة السلوك التنظيمي',tracks:[{name:'الممارس',batches:[{name:'OBM-1'}]}]},{name:'ادارة السلوك التنظيمي',tracks:[{name:'الممارس',batches:[{name:'OBM-1'}]}]});students.push({_fbKey:'obm1',program:'شهادة إدارة السلوك التنظيمي',batch:'OBM-1'},{_fbKey:'obm2',program:'إدارة السلوك التنظيمي',batch:'OBM-1'});performanceRender();});assert.equal(await page.evaluate(()=>performanceSemesterResults(performanceModel()[0].batches.values().next().value)[0].absent),1);assert.deepEqual(await page.evaluate(()=>{const p=performanceModel().filter(p=>performanceProgramKey(p.name)==='ادارة السلوك التنظيمي');return [p.length,p[0].students.length,p[0].batches.size]}),[1,2,1]);assert.equal(await page.locator('.performance-absent-counter').count(),2);
await page.getByLabel('ساعات إنتاجية محاضر أ',{exact:true}).fill('12.5');await page.getByLabel('ساعات مكتبية محاضر أ',{exact:true}).fill('3.25');await page.getByLabel('ساعات إنتاجية محاضر ب',{exact:true}).fill('8');await page.getByLabel('ساعات مكتبية محاضر ب',{exact:true}).fill('2');assert.equal(await page.locator('#performanceHoursTotal2').innerText(),'25.75');assert.equal(await page.locator('#performanceHourRowTotal0').innerText(),'15.75');assert.equal(await page.evaluate(()=>writes.length),0);
await page.locator('[data-hour-save="0"]').click();await page.waitForFunction(()=>writes.length===1);assert.equal(await page.evaluate(()=>writes[0].path),'lecturerProductivity/2026-10/L');assert.equal(await page.evaluate(()=>lecturerProductivityData['2026-10'].L.extraHours),7);assert.equal(await page.evaluate(()=>lecturerProductivityData['2026-10'].L.note),'preserve');assert.equal(await page.evaluate(()=>writes[0].payload.productiveHours),12.5);
await page.getByLabel('ساعات إنتاجية محاضر ب',{exact:true}).fill('-1');await page.locator('[data-hour-save="1"]').click();assert.equal(await page.evaluate(()=>writes.length),1);await page.getByLabel('ساعات إنتاجية محاضر ب',{exact:true}).fill('8');
await page.evaluate(()=>performanceFilter('period','2026-11'));assert.equal(await page.locator('#performanceHoursTotal2').innerText(),'0');await page.evaluate(()=>performanceFilter('period','2026-10'));assert.equal(await page.locator('#performanceHoursTotal2').innerText(),'25.75');
await page.addScriptTag({path:'productivity-ledger.js'});
await page.evaluate(()=>{lecturerProductivityData['2026-10'].L.meetings={meeting_test:{durationMinutes:135}};performanceRender();});
assert.equal(await page.locator('#performanceHourRowTotal0').innerText(),'18');
await page.locator('[data-hour-save="0"]').click();await page.waitForFunction(()=>writes.length===2);
assert.equal(await page.evaluate(()=>writes[1].payload.productiveHours),12.5);assert.equal(await page.evaluate(()=>lecturerProductivityData['2026-10'].L.meetings.meeting_test.durationMinutes),135);
await page.screenshot({path:'.tools/performance-preview.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>{performanceState.evaluationState='idle';secureAdminExamRequest=async()=>{throw Error('offline')};return renderPerformance();});assert.match(await page.locator('#performanceContent').innerText(),/تعذر تحميل التقييمات/);
await page.evaluate(()=>{currentUser={role:'lecturer'};document.getElementById('performanceContent').innerHTML='';return renderPerformance();});assert.equal(await page.locator('#performanceContent').innerText(),'');await browser.close();console.log('PASS: merged QBA/QASP cohorts, removed student analysis, semester pass/tested/absent/partial counts, OBM excluded, charts, manual hours and totals, preserved fields, no automatic writes, invalid hours, month isolation, drafts, mobile, API failure, admin guard');})().catch(e=>{console.error(e);process.exit(1)});
